### ISSUE TITLE
Do I need to sign .Net Foundation contribution Agreement for Pull Requests?

### ISSUE THREAD

**Issue by garora** [aspnet/WebHooks#1]
This is not an issue, its just a query. I would like to make pull request lets say request is related to updation of ```ReadMe.md``` file. So, do I need to sign ```.Net Foundation contribution agreement?``` . Please label this as ```query``` instead of an ```issue```.

**Comment by Eilon** [comment]
In general you need to sign a [.NET Foundation Contributor License Agreement](https://cla2.dotnetfoundation.org/), as indicated in the [contributing](https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md) document.

There's an automated bot that scans every pull request to determine whether the agreement is required. Certain small changes do not require any agreement. If you send a pull request the bot will flag the pull request with the appropriate information.
