### ISSUE TITLE
Salesforce Receiver does not enforce XML response

### ISSUE THREAD

**Issue by markdulfer** [aspnet/WebHooks#101]
When the Salesforce receiver returns an error response, eg. for bad organisation id, it does not force the response to be XML formatted. This means that the response may go back as JSON, depending on what else is in the web app. This causes Salesforce to not record the actual error because it can't parse a JSON response.

Can the response in ReceiveAsync be changed from

`request.CreateErrorResponse(HttpStatusCode.BadRequest, msg);`

to

`request.CreateResponse(HttpStatusCode.BadRequest, msg, context.Configuration.Formatters.XmlFormatter);`

or is there a better way to do this?

**Comment by HenrikFrystykNielsen** [comment]
That makes sense. I assume it requires an actual SOAP Error?

**Comment by markdulfer** [comment]
My understanding of Salesforce is that it doesn't need to be an actual SOAP error, it just needs an XML formatted response. It is able to parse an XML response to display a sensible message in the outbound workflow monitoring page. It will display the contents of the msg variable passed into the CreateResponse call. When a JSON response is received, it is not able to parse the string, so displays an error message that says something along the lines of 'invalid XML response blah blah blah'.

In my current app I've done a workaround which force the webhook response to be XML by using a custom ContentNegotiator. It would be nice not to have to do this though.

In the Register method in my WebApiConfig class I call this:

`            config.Services.Replace(typeof(IContentNegotiator), new CustomContentNegotiator());
`

and in the Negotiate method of the CustomContentNegotiator class I just have a simple if/else:

```
if (HttpContext.Current.Request.Url.PathAndQuery.Contains("webhooks/incoming/sfsoap"))
	return new ContentNegotiationResult(
		_xmlFormatter,
		new MediaTypeHeaderValue("application/xml"));
else
	return new ContentNegotiationResult(
		_jsonFormatter,
		new MediaTypeHeaderValue("application/json"));
```

**Comment by HenrikFrystykNielsen** [comment]
ok, I updated the dev branch to send SOAP errors in most cases, see 69522e6980ac83f2b35718df1d4666bc7c45cbda

**Comment by markdulfer** [comment]
Looks good, thank you.
