### ISSUE TITLE
Need option to not verify filters upon registration

### ISSUE THREAD

**Issue by memilavi** [aspnet/WebHooks#104]
Here is my scenario:
I have an application that accepts telemtry from various sources. The telemetry consists of 1000's of data fields.
My clients need the ability to subscribe to a specific field's received event, ie. the "FirstName" field was received.
Since, as mentioned above, there are 1000's of fields, I don't want to create 1000's of filters ahead.
What I would like is some kind of Ad-Hoc Filters, meaning - the client can subscribe to a non-exist events, and get notified when they occur.
Now, there is no problem in the Publish phase - the `NotifyAsync ` method can accept non-exist filter names and send them to the subscribers.
The problem lies in the Registration phase. The `WebHookRegistrationsController `specifically validates the Filters collection of the `WebHook`, and makes sure the filters specified there exist. 
I would like to have an option to override this validation, and allow the subscribers to subscribe to non-existent filters.

Thanks!

**Comment by HenrikFrystykNielsen** [comment]
I think the right solution here is for me to make it easier to write your own controller and then have the validation happen on the side., i.e. have something you can call into. This will also address #88. I will send out an update when ready.

**Comment by memilavi** [comment]
Thanks!

In the meantime, how can I substitue the current controller with a custom one? Is it possible?

**Comment by HenrikFrystykNielsen** [comment]
Yes, it is straight forward to creating your own controller -- you can copy most of the existing controller  [1]and then modify as you see fit.

[1] https://github.com/aspnet/WebHooks/blob/master/src/Microsoft.AspNet.WebHooks.Custom.Api/Controllers/WebHookFiltersController.cs

**Comment by HenrikFrystykNielsen** [comment]
I just committed 757530d2af40da1d51e0cf387595561e1e5cebf0 which makes it much simpler to write your own WebHook registration mechanism whether that is a separate API controller, an MVC controller, or something else entirely. This also gives you full control over how much verification you want to do. Please see the commit for details -- you might be able to look at the existing WebHookRegistrationsController.cs for an example of how it is used.
