### ISSUE TITLE
Is it possible to create WebHooks for third parties which actually do not provide facility?

### ISSUE THREAD

**Issue by garora** [aspnet/WebHooks#11]
Might be this is not a related. Just a thought can I implement WebHooks for third parties like Resellerclub which only provides Rest API support. If yes, then do I only need to call their API ?

**Comment by HenrikFrystykNielsen** [comment]
In some cases, I believe you can, but you have to be a bit creative :) Imagine that you have a Web App which you use to poll the third-party site for changes and when it detects something it sends a WebHook to registered parties.

**Comment by garora** [comment]
Thanks @HenrikFrystykNielsen I get the idea. So, in that case I have to create some interface which send notification (what we said Webhooks).
