### ISSUE TITLE
Creating an array in CreateWebHookRequest instead of a JSon object

### ISSUE THREAD

**Issue by divad4686** [aspnet/WebHooks#115]
I'm building a Webhook provider library, and one of the requirements I have is to change the default Webhook request body. I can do this by overriding the CreateWebHookRequestBody in the [WebHookSender  class](https://github.com/aspnet/WebHooks/blob/master/src/Microsoft.AspNet.WebHooks.Custom/WebHooks/WebHookSender.cs#L126).

The problem is that my request body have to be wrapper in an array ( it is a requirement for [Rest Hooks in Zapier](https://zapier.com/developer/documentation/v2/rest-hooks/#step-2-sending-hooks-smallema-call-from-your-app-to-zapieremsmall)) but the functions CreateWebHookRequest, CreateWebHookRequestBody and SignWebHookRequest all work with JObject class, making it impossible to wrap the body in an array.

I fixed this by overriding the 3 functions in my own class, but most of the work was copy-pasting the default implementation, replacing JObject for JContainer and using JArray.FromObject in CreateWebHookRequestBody.

I think I could do a pull request here in the project with this [commit](https://github.com/aspnet/WebHooks/compare/master...divad4686:master) so people will have it easy later to use JArray or JObject in their own implementations. This should not have any side effect, since in the end, outside CreateWebHookRequestBody, all it is done with this object is a. [.ToString()](https://github.com/aspnet/WebHooks/blob/master/src/Microsoft.AspNet.WebHooks.Custom/WebHooks/WebHookSender.cs#L182)

 The only problem I could see is that it would not compile the project for people that already override CreateWebHookRequestBody

**Comment by hybridtechie** [comment]
It's much easier to use Zapier scripting and wrapping the response in an array.

**Comment by dougbu** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

Have also marked this issue as up-for-grabs. This means we will review a PR filling this gap if someone submits one.

In this particular case, the PR should avoid breaking changes and continue to support those who have overridden the existing methods. Add new wrapper methods e.g. `CreateWebHookRequestBodyContainer(...)` and call the existing overloads. Then use the new wrappers in `CreateWebHookRequest(...)`.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspNetWebHooks#24
