### ISSUE TITLE
Support for Slack slash commands

### ISSUE THREAD

**Issue by brantb** [aspnet/WebHooks#12]
[Slash Commands](https://api.slack.com/slash-commands) are a slight variant of Outgoing Webhooks which have a `command` parameter instead of a `trigger_word` parameter and do not include the command in the `text` parameter. Also, according to the API docs the response can be plain text instead of JSON.

I took a crack at implementing this myself, but it ended up being not-very-DRY and I wasn't sure what the best way to approach the problem would be.

**Comment by HenrikFrystykNielsen** [comment]
Added support for slash commands with commit 9b32424cb35e5d66f41e966aff36fb005c47df3a This will make it into Nugets with the next drop. I also added a sample receiver illustrating how to use both trigger based WebHooks and Slash Commands.
