### ISSUE TITLE
Webhook sender real example require

### ISSUE THREAD

**Issue by shahzadgodil** [aspnet/WebHooks#120]
Hello,

I am looking for real life Webhook example. 

I want to implement Webhook “SENDER” for sending events to Zapier in my ASP.net application.

I want to send AddCustomer and DeleteCustomer event from my application to Zapier App event. 

How I can write code for  send JSON data in  AddCustomer and DeleteCustomer function? What exact functions will be called of WebHook classes in AddCustomer and DeleteCustomerc?

I have also see this sample for implementing Webhook Sender. But I didn’t find any real life example in it
https://blogs.msdn.microsoft.com/webdev/2015/09/15/sending-webhooks-with-asp-net-webhooks-preview/

Thanks
Shahzad

**Comment by garora** [comment]
@shahzadgodil - have you gone through these [WebHook](https://social.technet.microsoft.com/wiki/contents/articles/tags/webhooks/default.aspx) ?

**Comment by shahzadgodil** [comment]
https://blogs.msdn.microsoft.com/webdev/2015/09/15/sending-webhooks-with-asp-net-webhooks-preview/

The receiver examples are quite clear and giving you real life example. But sender examples are not in detail. How can I send data  from my AddEmployee via webhook with actual data 

I want code example

**Comment by dougbu** [comment]
The [Custom Sender sample](https://github.com/aspnet/WebHooks/tree/78491ef819c26d85a0441a572569fa2ec96d8935/samples/CustomSender) is the best place to start.

The basic requirement is to use the Microsoft.AspNet.WebHooks.Custom* packages and override the behaviour to match the Zapier protocol. The WebHooks sender implements a custom protocol, not Zapier's. Suspect overrides will mainly be to methods in the `WebHookSender` subclass that makes sense in your scenario.
