### ISSUE TITLE
Want to send data to Zapier using Webhook 

### ISSUE THREAD

**Issue by shahzadgodil** [aspnet/WebHooks#121]
Hello,

I want to send data to Zapier for notifying events in Zapier. For example, whenever there will be Add or delete of employee record in my application, I want to raise event to Zapier with data.

After receiving data in zapier, I can then create actions there.

Should I use Webhook.sender or webhook.receiver?

Thanks

**Comment by divad4686** [comment]
If you want to send data to Zapier after some event occur in your application, you have to use the sender.

If you want to receive data from zapier after an action from another app you just need to point zapier to your API end point.

From your first Paragraph it looks like you want to use the sender, I'm implementing this right now and it is working, I may write a blog post about this later, but if you need any help you can ask here.

Check this issue from me https://github.com/aspnet/WebHooks/issues/115 because it is related to Zapier and you may need to do the same inheritance.

**Comment by shahzadgodil** [comment]
Hello,

Thank for your prompt reply

This is exactly what I understand. But in this example, event is firing from client application (receiver) and not from sender
https://blogs.msdn.microsoft.com/webdev/2015/09/15/sending-webhooks-with-asp-net-webhooks-preview/

Would you give a simple example for implementing it. How I can raise even with data whenever there is AddEmployee in my application?

**Comment by divad4686** [comment]
What DB are you using?

**Comment by shahzadgodil** [comment]
SQL Server

**Comment by shahzadgodil** [comment]
Any update?

**Comment by divad4686** [comment]
I'm a bit busy right now, I can answer for extensively tomorrow, but you need to check the Microsoft.AspNet.WebHooks.Custom.SqlStorage project here in the repo, and then use Microsoft.AspNet.WebHooks.Custom

The problem with the blog post in your comment is that it is an example to trigger webhooks in a MVC controller, but I'm guessing you need to trigger it from another part of your domain, so you need to read a bit the code in the repos, and try to use their classes. 

I have been thinking about writing a blog post about this when I have a bit more time :)

Start with the SqlStorage project, read the Readme and run the migration on your database.

**Comment by shahzadgodil** [comment]
Thank you very much for you reply

I am able to download and setup SqlStorage.

Regarding your second point:
I will see code also but first I want understanding in this Microsoft blog
http://www.awesomescreenshot.com/image/2267757/2b803aaf8962b10dacd1e21f91f9649c

See red squared text. This even is triggering from Client (Receiver) from HTML page. How I can I raise event from Webhook sender?

**Comment by shahzadgodil** [comment]
Any update about article: 

I am trying to get Microsoft sample application in Zapier
https://blogs.msdn.microsoft.com/webdev/2015/09/15/sending-webhooks-with-asp-net-webhooks-preview/

This sample application is available on 
test.livetecs.com. 

I am trying to implement this test webhook application in Zapier. But I am getting error
http://www.awesomescreenshot.com/image/2280829/e2a64751f6e7ccd2f41048f68a513474

Please suggest

Shahzad Godil

**Comment by dougbu** [comment]
Original questions in this issue have been answered.

The basic requirement is to use the Microsoft.AspNet.WebHooks.Custom* packages and override the behaviour to match the Zapier protocol. The WebHooks sender implements a custom protocol, not Zapier's. Suspect overrides will mainly be to methods in the `WebHookSender` subclass that makes sense in your scenario.
