### ISSUE TITLE
Custom Authentication in Sender webhook

### ISSUE THREAD

**Issue by shahzadgodil** [aspnet/WebHooks#122]
Hello,

I am going to use Webhook sender in my existing application. How can I use custom authentication in webhook sender?

Shahzad Godiol

**Comment by Marusyk** [comment]
Any status? I need the same thing

**Comment by dougbu** [comment]
The `WebHookSender` class and its in-box subclasses expose `virtual` methods for many types of customization, In this case, override `SignWebHookRequest(...)` to instead authenticate as part of your application.
