### ISSUE TITLE
must contain a 'echo' query parameter: Zapier

### ISSUE THREAD

**Issue by shahzadgodil** [aspnet/WebHooks#123]
I am trying to get Microsoft sample application in Zapier https://blogs.msdn.microsoft.com/webdev/2015/09/15/sending-webhooks-with-asp-net-webhooks-preview/

This sample application is available on test.livetecs.com.

I am trying to implement this test webhook application in Zapier. But I am getting error

Bargle. We hit an error fetching a event2. :-( Error: test.livetecs.com returned (400) Bad Request and said "The WebHook verification request must contain a 'echo' query parameter which will get echoed back in a successful response."

Screenshot of Zapier application http://www.awesomescreenshot.com/image/2283523/fc8013da6e80563642b4b0ea782b26f5

Web based Time and Expense Tracking Software with ASP.net source code
<a href="http://www.livetecs.com/">Time and Expense Software</a>

**Comment by dougbu** [comment]
It seems your customization of the WebHooks sender behaviour to match Zapier is incomplete.

The basic requirement is to use the Microsoft.AspNet.WebHooks.Custom* packages and override the behaviour to match the Zapier protocol. The WebHooks sender implements a custom protocol, not Zapier's. Suspect overrides will mainly be to methods in the `WebHookSender` subclass that makes sense in your scenario.
