### ISSUE TITLE
Error when running the sample of generic receiver

### ISSUE THREAD

**Issue by Mazenx** [aspnet/WebHooks#125]
Hello,
      I made a change that I dont want the generic json receiver to check for the code parameter in the url , but when ever I am trying to deploy the new dll's to my app I am getting this error
"Could not load file or assembly 'Microsoft.AspNet.WebHooks.Common' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)"

so I decided to run the original genericreceiver in the samples , and apparently the original one is also having the same error , any ideas?

This is the change I made by commenting these lines

```
    if (string.IsNullOrEmpty(code))
            {
                //string msg = string.Format(CultureInfo.CurrentCulture, ReceiverResources.Receiver_NoCode, CodeQueryParameter);
                //request.GetConfiguration().DependencyResolver.GetLogger().Error(msg);
                //HttpResponseMessage noCode = request.CreateErrorResponse(HttpStatusCode.BadRequest, msg);
                //throw new HttpResponseException(noCode);
            }
```

**Comment by HenrikFrystykNielsen** [comment]
If you run the code directly from the repo then you have to run this from a command prompt from the root of the repo:

    build.cmd EnableSkipStrongNames

Hope this helps

**Comment by dougbu** [comment]
Question has been answered.
