### ISSUE TITLE
Swagger specification on WebhookRegistrations controller

### ISSUE THREAD

**Issue by yvdh** [aspnet/WebHooks#127]
Hi,
I think it would be nice if the WebHookRegistrations controller would be decorated correctly  with its http response codes, e.g. SwaggerResponse("201", typeof(WebHook))  for Post. As it stands now this doesn't show up in the swagger file, and generating a client library for registrations leads to incorrect code (partly due to the generator, admittingly).

Or am I missing something?

Yves

**Comment by dougbu** [comment]
Thank-you for this enhancement suggestion. At this time, we have no plans to implement this request.

ASP.NET WebHooks does not currently have a Swagger or Swashbuckle dependency and such a dependency would not be appropriate in many cases. Suggest instead subclassing `WebHookRegistrationsController` to add the attributes you prefer or copy the code into your application..
