### ISSUE TITLE
Stripe Handler not reached

### ISSUE THREAD

**Issue by MatteoMichelotti** [aspnet/WebHooks#129]
Hello,
I'm trying to setup webhooks from Stripe, but I don't understand what I'm doing wrong. I'm following the instruction shown here: https://docs.microsoft.com/en-us/aspnet/webhooks/
I first installed the NuGet Microsoft.AspNet.WebHooks.Receivers.Stripe package, then added the app setting key for Stripe in Web.config using Stripe's secret key ( `<add key="MS_WebHookReceiverSecret_Stripe" value="sk_test_****" />`). Next, I initialized the WebApiConfig with `config.InitializeReceiveStripeWebHooks();` and created a StripeHandler class to handle the processing phase.

![image](https://cloud.githubusercontent.com/assets/16746827/24820143/2e47b654-1bad-11e7-8280-bc1ed9048eda.png)

In Stripe, I'm sending a test webhook to **url**/api/webhooks/incoming/stripe?code=**key**
but nothing happens and after a little while I get a timeout error...
BTW, I'm using a tunnel application (called ngrok) so I can test the webhook without having to publish the site everytime

Please, can somebody tell me, in Leyman's terms, what I'm doing wrong and how to fix it?
Thank you very much!

Matteo

**Comment by garora** [comment]
@MatteoMichelotti -Try this, it is working for me: ```https://<host>/api/webhooks/incoming/stripe/{id}?code=secret_key```

**Comment by MatteoMichelotti** [comment]
Thank you for the reply, though I already solved my problem, I wasn't setting up the receiving controller properly.

**Comment by dougbu** [comment]
All questions appear answered. @MatteoMichelotti please reopen if I missed something.
