### ISSUE TITLE
Is it possible to add custom header as part of web hook sender

### ISSUE THREAD

**Issue by renjurajwm** [aspnet/WebHooks#138]

**Comment by HenrikFrystykNielsen** [comment]
Yes, you can see a sample of how to do this here: 

https://github.com/aspnet/WebHooks/blob/master/samples/CustomSender/WebHooks/MyWebHookSender.cs

Here you can see how to register it:

https://github.com/aspnet/WebHooks/blob/master/samples/CustomSender/App_Start/WebApiConfig.cs

Hope this helps,

Henrik

**Comment by renjurajwm** [comment]
Thanks Henrik

**Comment by dougbu** [comment]
Question has been answered.
