### ISSUE TITLE
How do we log the webhook http request and response 

### ISSUE THREAD

**Issue by renjurajwm** [aspnet/WebHooks#139]
I am planning to capture the Webhook Calls to Application Insights,  How can i get the actual Request and Response Information for each webhooks.

**Comment by dougbu** [comment]
Suggest either searching around the [Azure Portal](https://portal.azure.com) for such low-level logging or enabling logging for the service hosting your WebHooks application. In Azure, the Activity log tab for the relevant alert at least shows the alert's JSON. And, if your application is running in an Azure App Service, enable Application Logging (on the Diagnostic logs tab) -- perhaps using the Log Stream to observe in real time.
