### ISSUE TITLE
More descriptive project URL for packages

### ISSUE THREAD

**Issue by shiftkey** [aspnet/WebHooks#14]
After seeing the initial blog post I wanted to dig into the code (I was exploring ideas in this vein for the octokit.net project) but the first place I looked was the NuGet package's project site. Seeing it was pointing at "www.asp.net" made me a bit sad: https://github.com/aspnet/WebHooks/blob/1.2.0-beta/src/Microsoft.AspNet.WebHooks.Receivers.GitHub/Microsoft.AspNet.WebHooks.Receivers.GitHub.nuspec#L10

I eventually found it via @shanselman's blog post: http://www.hanselman.com/blog/IntroducingASPNETWebHooksReceiversWebHooksMadeEasy.aspx

I appreciate that it's early days, but I'd love to see a more specific URL than "www.asp.net" to help discoverability of how to use these packages and how to get involved.

**Comment by Eilon** [comment]
We can probably set it to the GitHub project URL for now.

**Comment by HenrikFrystykNielsen** [comment]
@shiftkey I updated the project link to point to the online documentation at 'http://docs.asp.net/projects/aspnetwebhooks'. There you can find a link to the repo and more. Hopefully that is more descriptive :)

**Comment by shiftkey** [comment]
@HenrikFrystykNielsen that looks great! Thanks!

I'll close this out now rather than wait for the next package release...
