### ISSUE TITLE
Access to the path '<user>\AppData' is denied.

### ISSUE THREAD

**Issue by khoait** [aspnet/WebHooks#142]
I am using SQL Storage for my web api. I set the MS_SqlStoreConnectionString connection string in the web.config file. It's working as expected on my dev machine. But when deployed to IIS, I got this exception when register a new web hook.

`Access to the path '<user>\AppData' is denied.`

I tried setting write permission for NETWORK SERVICE but it didn't work.

Please help.

**Comment by khoait** [comment]
I got a different exception when I set write permission for IIS_IUSER:

`General error during 'Insert' operation: 'The system cannot find the file specified.`

Not sure what file it's trying to access during insert when I am using sql storage.

**Comment by dougbu** [comment]
Closing as the configuration question seems to be about IIS or SQL and is not WebHooks-related.

FYI one suggestion: Use a more-full-featured SQL server or include login information in your configured connection string.
