### ISSUE TITLE
[WebHooks.Receivers.VSTS] WorkItemUpdatedFields is limited to a few predefined system fields

### ISSUE THREAD

**Issue by NenoLoje** [aspnet/WebHooks#143]
This issue is for: **Microsoft.AspNet.WebHooks.Receivers.VSTS**

The [`WorkItemUpdatedFields`](https://github.com/aspnet/WebHooks/blob/master/src/Microsoft.AspNet.WebHooks.Receivers.VSTS/Payloads/WorkItemUpdatedFields.cs) class has **9** fields defined.

VSTS offers many more fields (system and custom ones) that could be part of this event as well. This does not seem to be implemented currently.

Questions:

1. How can I access other **custom fields**? Any plans to extend this class?
2. Would you be **willing to accept PRs** for other built-in system fields (like `System.IterationPath``)?

Thanks,
--Neno

**Comment by dougbu** [comment]
Suggest binding to a `JObject` and using the `WebHookReceiverContext` to get that type.

**Comment by danroth27** [comment]
We should look at improving this experience for ASP.NET Core as part of #182

**Comment by dougbu** [comment]
Pending work on #182, marking this up-for-grabs and putting it into the Backlog. If someone has VSTS fields e.g. @NenoLoje's `System.IterationPath` they would like to add, send a PR.

**Comment by aspnet-hello** [comment]
This issue was copied to aspnet/AspNetWebHooks#20

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspLabs#51
