### ISSUE TITLE
Adding a Chargebee receiver

### ISSUE THREAD

**Issue by fabiodaniele** [aspnet/WebHooks#147]
Hi all,
I'd like to contribute to this project by adding a receiver for Chargebee webhooks.

Can I do it? :)

**Comment by garora** [comment]
@fabiodaniele - You can create a `PR` as this is an open source you can contribute rest the final decision would be of @HenrikFrystykNielsen

**Comment by fabiodaniele** [comment]
@garora  - Ok, thanks.

**Comment by aspnet-hello** [comment]
This issue was copied to aspnet/AspNetWebHooks#21

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspLabs#50
