### ISSUE TITLE
Multiple hooks error

### ISSUE THREAD

**Issue by Nostreum** [aspnet/WebHooks#148]
Hi ! 

I've created a WebHook controllers for an internal instance of Gitlab, everything is working locally. 
I just deployed it to an IIS and i've a weird issue : Same hooks are received multiple times. For example if i do the following actions : 

- new issue
- new comment

On my computer i receive 2 hooks (1 issue and 1 comment) and on IIS i receive 3 hooks (1 issue then 1 issue and 1 comment). It's like hooks are "saved" somewhere and got "re-called" with the next Hook. 
If someone has a idea...

Thank's.

**Comment by garora** [comment]
@Nostreum - Have your written any custom code for it? I did the same and I am receiving same on local and on IIS. I used sample code.

**Comment by Nostreum** [comment]
@garora No the code is exactly the same... Apparently, sometimes IIS takes too long to answer, so gitlab decide that the hook failed and retry it. Locally it takes between 250 and 350 ms, and 900-1100 on IIS. 
I've build a temporally solution (saving hook's id), but I don't know how to resolve this properly.

**Comment by garora** [comment]
@Nostreum - Its really a weird issue. Are there any specific steps so that I can recreate this issue at my end. I tried the same code on a new box and that is working as a charm.

**Comment by Nostreum** [comment]
@garora I've configured an HTTPS site, without any specific steps... To be sure i just created an other one and i get the same issue. 
I've done more tests. When i press the "Test" button on gitlab (to send a hook), the IIS receive it 11-12 seconds later : 
- Press testbutton at X seconds
- The first line of code is executed X+12 secondes later
- Then X+13 seconds i got the response.

I tried to send a POST request with postman, and i got the same problem : 
![postman](https://user-images.githubusercontent.com/10847525/28833882-fc428b90-76e0-11e7-8a98-df2484dbdb19.PNG)

I don't know a lot of thing about IIS so maybe something happen here, like a "queue" or something..

**Comment by garora** [comment]
I did try locally and over my private Git not sure if your issue is related Gitlab. @HenrikFrystykNielsen would give the insight on this.

**Comment by Nostreum** [comment]
I found the problem : My site become "off" on IIS, so when i send a new hook, it takes some time to restart. But, the site go off after like 20-30 secs of inactivity. I tried some solutions but nothing work (AlwaysRunning mode, disabled idle-timeout etc), if you have an idea ..

**Comment by Nostreum** [comment]
Well, i solve my problem... My log file was in the bin folder, each time i modify it, the bin folder changed, and my application was recycled. This is why for each hook my site needed to restart...

**Comment by garora** [comment]
@Nostreum - great you find the solution for your problem.
