### ISSUE TITLE
Build errors with non-English .NET

### ISSUE THREAD

**Issue by fabiodaniele** [aspnet/WebHooks#150]
Hi, 
I cloned the repo and tried to build it with the build.cmd script, but it fails due to many errors occurring in many test projects.

Could it depend on the configuration of my development environment? 

My machine has Visual Studio 2017 installed.

**Comment by Eilon** [comment]
@fabiodaniele can you show some examples of the errors you're getting?

**Comment by garora** [comment]
@Eilon, @fabiodaniele  - is it something  related to [Issue#92 ](https://github.com/aspnet/WebHooks/issues/92) ?

**Comment by Eilon** [comment]
@garora not sure, but we're working on getting this repo updated for ASP.NET Core, so I'm sure we'll have everything building.

If people can share the exact error(s) they're getting, plus info on the exact version of Visual Studio installed, that would be helpful!

**Comment by fabiodaniele** [comment]
@Eilon @garora hi, sorry for the delay.

The log generated by the build command shows errors related to the execution of the test projects. Many exceptions are raised.

@garora It seems something really different from the issue you mentioned.

Here is a file containing the whole log as copied from the console window.
[webhooks build errors.txt](https://github.com/aspnet/WebHooks/files/1238164/webhooks.build.errors.txt)

_Note_
As I wrote, I use Visual Studio 2017.

I spent some effort in understand that, for the solution to build in Visual Studio, I needed to install the FxCop extension (never used before). But I'm not sure that my local dev environment is correct to build this solution.

What I mean is: without other info, I just can think I could need other extensions or I need to use another VS version. 

So, imho, I believe it would be useful to write some docs about the correct configuration to work with the solution.

**Comment by garora** [comment]
@fabiodaniele - I do not have 'Visual Studio 2017' installed on my current box, I could try the same within next couple of hours from now.

I did a try using Visual Studio 2015 Update3 and project is building perfectly using both Visual Studio and Build.bat file.

This is just a vague guess, nothing tested yet. Build.bat is using msbuild.exe 14.0 - please check if you have other exceptions related to msbuild version. Also, if required you can take a look here: [Visual Studio 2017 msbuil](https://stackoverflow.com/questions/42696948/how-can-i-install-the-vs2017-version-of-msbuild-on-a-build-server-without-instal)

**Comment by fabiodaniele** [comment]
@garora I can't find any exception referring to msbuild.

The exeptions I see are raised by Assert._SomeAssertion_(), but they don't seem related to msbuild.

If I look at the first lines in the log, I find:
`Microsoft (R) Build Engine versione 14.0.23107.0`,
do you think this to be the reason for the errors?

Anyway, now I try to also look at the link you suggested :-)

**Comment by garora** [comment]
@fabiodaniele - I can't say anything until I tried it using Visual Studio 2017 update3 (latest one). I will try and post here after several hours. I am sorry, I can't do it right now due to unavailability of Visual Studio 2017 on my dev box.

**Comment by fabiodaniele** [comment]
@garora Don't worry! In the meanwhile, I try to replicate the issue on another (newer and cleaner) PC, hoping to find out more.

**Comment by garora** [comment]
@fabiodaniele - best of luck and thanks

**Comment by garora** [comment]
@fabiodaniele - It seems, issues are with Visual Studio 2017. Give me some time to analyze and I come back with more information.

**Comment by Eilon** [comment]
Thanks for the extra info, we'll investigate. Just to be clear, these are *test* failures, not *compilation* failures (which confused me, because in my mind "build" == "compile"), but I get that build.cmd runs everything, and it's failing.

**Comment by garora** [comment]
@fabiodaniele - I tried on a new Dev box with a fresh install of Visual Studio 2017 Preview, here are the steps:
P.S. I have already cloned the repository [[garora/WebHooks]](https://github.com/garora/WebHooks)
1. Open command prompt `win+R`
2. Moved to my repository directory
3. Initaited `build.cmd` --- Got StringName error
4. Disabled strongName  `build.cmd EnableSkipStrongNames`
5. Again initiated `build.cmd` 

Everything is passed and Build successful `Time Elapsed 00:28:45.36`.
You can check [Build log](https://github.com/aspnet/WebHooks/files/1240488/msbuild.txt)

I suggest, drill-down the failing tests eg. `Microsoft.AspNet.WebHooks.Common.Test` is failing for you that should not be.

@Eilon - This is working for me as expected. I would appreciate if you can look into the issue #92 that is a roadblock for #15

**Comment by fabiodaniele** [comment]
@Eilon - Yes, those are _test_ failures, so I'm sorry that the title I used for this issue may have confused you.

@garora - This is really strange to me, because I did the same thing. Also, I can notice that the log you attached is not the console output generated by _build.cmd_. So It's hard for me to believe that the issue is not replicating on your new dev box.


Anyway, the point for me is: 
if the my dev environment is wrong, I'd like to know which is the correct one (VS version, extensions needed and so on), so I can be sure to contribute to the project without doubts about quality.

I already tried to develop what I proposed with the issue #147, but:
- I had to do some reverse engineering of the solution to understand that VS needs some extensions to be installed 
- after this, I had to make a lot of hacking to make the new projects I added in the solution to be compatible with the existing solution conventions (such as FxCop and the build.cmd script)
- then, the tests I've written for the new receiver, even if written in the same way (at least, is what I think to have done) as the others currently existing in the solutions, fail in a similar fashion when executing the build script.

In my opinion, the problem is not about the fails themselves. The problem is that I don't think this to be an acceptable workflow. And, always in my opinion, this is due to a lack in informations on about collaborating to the project. 

I don't think it's enough to ask new contributors to sign an agreement. I think it is also (and above all) important to share some documents about the proper configuration of the dev environment needed for collaborating to the project.

I'm really sorry for critizing, but I hope you'll really understand that I am doing this for constructive and collaborative purposes.

And I really thank you for all the support :-)

**Comment by garora** [comment]
@fabiodaniele - First of all, I understand you are running through lot of issues. Don't worry, it happened in a dev's life. Regarding log, I attached is a log generated from `buil.cmd` and can be found in bin folder. Regarding your question about the Visual Studio version - `Visual Studio 2015 or later` .
Regarding your suggestions for documentations, I agreed with you, I am the one who is contributing since inception of this repository, so, I knew what all are required to execute the repository. Give me time to prepare a doc for this. Meanwhile, we can connect offline, I would be happy to help.

**Comment by fabiodaniele** [comment]
@garora Thank you :-)

**Comment by Eilon** [comment]
Indeed, we are working as hard as we can to get this repo back into shape - we let it go a little bit stale for a while so sorry about that.

**Comment by garora** [comment]
@Eilon - Thanks for your reply. I will wait until it get back. Just a thought - the issue, I was mentioned in not related to ASP.NET WebHooks, I believe that is a generic issue, where Visual Studio is unable to find the symbols. Is there any way, we can check with Visual Studio folks or is there any other platform, where I can ask this query?

**Comment by Eilon** [comment]
@garora the built-in "VS Feedback" tool is the best way to report issues with VS. That will send the right diagnostic info and get routed to the sub-team within VS who can investigate.

**Comment by garora** [comment]
@fabiodaniele - I've written a free ebook on WebHooks, it'd be helpful: [free ebook](http://gaurav-arora.com/book/954-book-asp-net-webhooks-succinctly).

**Comment by dougbu** [comment]
Looks as if some of the tests are culture-specific. The [webhooks build errors.txt](https://github.com/aspnet/WebHooks/files/1238164/webhooks.build.errors.txt) file shows Italian error messages where English is expected.

These tests need something similar to ASP.NET Core's [`[ReplaceCulture]`](https://github.com/aspnet/Testing/blob/0ea0789b252934b20397e06a8e7022721fed43e5/src/Microsoft.AspNetCore.Testing/ReplaceCulture.cs) or the [earlier version](https://github.com/aspnet/AspNetWebStack/blob/da59ce7f2aa180515aee1e2650828a148899465d/test/Microsoft.TestCommon/ReplaceCultureAttribute.cs) from ASP.NET Web Stack.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspNetWebHooks#23
