### ISSUE TITLE
StripeEvent not compatible with latest API

### ISSUE THREAD

**Issue by mscrivo** [aspnet/WebHooks#154]
As of Stripe's 2017-05-25 API version, the request property changed from a string to an object.  This library has not been updated to account for that change. 

See https://stripe.com/docs/upgrades?since=2017-08-15#api-changelog for details of the change.

**Comment by dougbu** [comment]
Self-assigning since this will block full testing the Core port of the Stripe receiver.

**Comment by dougbu** [comment]
404480a
