### ISSUE TITLE
Documentation link not working on landing page.

### ISSUE THREAD

**Issue by NeelBhatt** [aspnet/WebHooks#16]
On landing page of WebHooks, there is a line in README.md file which is as below:

``Please see the initial documentation for details.``

Here documentation  contains a link but currently it is redirecting to a page which is not found.

Page is here:

https://github.com/aspnet/WebHooks

URL is as below:

http://docs.asp.net/projects/aspnetwebhooks/en/latest/

**Comment by Eilon** [comment]
@danroth27 even the link from https://docs.asp.net/en/latest/ under "Frameworks" to get to WebHooks returns a 404. Any idea?

**Comment by danroth27** [comment]
I'm working on getting this resolved.

**Comment by danroth27** [comment]
Fixed.
