### ISSUE TITLE
Use ASP.NET Core branching strategy

### ISSUE THREAD

**Issue by dougbu** [aspnet/WebHooks#166]
@Eilon the `dev` branch in this repo was previously ahead of `master` by six commits. Both were ahead of the `1.2.1-rtm` tag though just by one commit in `master`'s case. In any case, the history was very linear and that's no longer the case because PR #158 (922798f6) merged into `master` but not `dev`.

Should I merge / cherry-pick this commit / whatever to again place `dev` ahead of `master`?

Or, would you prefer I bring the newer commits over from `dev` to `master`, then kill the `dev` branch (with fire)? I suggest we don't need to have both `dev` and `master`, given the well-kept tags for older releases.

**Comment by Eilon** [comment]
We should do what we do everywhere in ASP.NET Core: `dev` is the newest branch, and we'll create branches for stabilization, and tags for releases.

**Comment by dougbu** [comment]
@Eilon I've merged `master` into `dev`. Please set `dev` to be the repo's default branch. Then, I'll delete `master` and this issue can be `3 - Done`.

**Comment by Eilon** [comment]
Ok `dev` is now the default branch. Please take this into account regarding any open PRs (because they'd all be on the wrong branch now).

**Comment by dougbu** [comment]
`master` is no more and all PRs are focused on `dev`.
