### ISSUE TITLE
Add support for web links

### ISSUE THREAD

**Issue by pascalberger** [aspnet/WebHooks#168]
As of version 2017.2 TFS seems to send only the following link with a `git.pullrequest.created` call:

```
"_links": {
  "web": {
    "href": "https://tfs.bbtlocal.ch/BBT/Infrastructure/_git/doc.infrastructure/pullrequest/1312#view=discussion"
   }
}
```

The payload should be enhanced to support the `web` link if available.

**Comment by dougbu** [comment]
Marked as working because #156 exists.

**Comment by dougbu** [comment]
e8be053
Thanks @pascalberger!
