### ISSUE TITLE
Add support for Stripe webhooks

### ISSUE THREAD

**Issue by mteper** [aspnet/WebHooks#17]
Stripe docs here:
https://stripe.com/docs/webhooks
https://stripe.com/docs/api#events

**Comment by HenrikFrystykNielsen** [comment]
We do have support for Stripe -- I just haven't written about it yet :) You can find it here: https://github.com/aspnet/WebHooks/tree/master/src/Microsoft.AspNet.WebHooks.Receivers.Stripe

**Comment by mteper** [comment]
My bad, closing. Thanks!
