### ISSUE TITLE
[Question] ASP.NET WebHooks or Microsoft ASP.NET Core WebHooks?

### ISSUE THREAD

**Issue by garora** [aspnet/WebHooks#170]
As per various threads, we'd be getting preview of WebHooks for ASP.NET Core. I am curious to know, are we going to rename this product something like ASP.NET Core Webhooks or it'd be remain unchanged?

**Comment by dougbu** [comment]
There will be two products: ASP.NET Core WebHooks and ASP.NET WebHooks. They will ship side-by-side as separate packages.
