### ISSUE TITLE
Simple Custom Webhook Receiver is not working 

### ISSUE THREAD

**Issue by abcplex** [aspnet/WebHooks#171]
I want to make a very simple webhook custom receiver for api.ai site. I have created a project using this sample, 
https://github.com/aspnet/WebHooks/blob/a735611fd0be052261fee0f3e37ff436f907fa34/samples/CustomReceiver/WebHooks

Web.config I have,

    <add key="MS_WebHookReceiverSecret_Custom" value="12345678901234567890123456789012"/>

But when I hit the url api/webhooks/incoming/custom/1 I am getting this error.

Could not find a valid configuration for WebHook receiver 'custom' and instance '1'. The setting must be set to a value between 32 and 128 characters long.

Please help.

**Comment by dougbu** [comment]
@abcplex either remove `/1` from the URL or change the configuration to
``` xml
<add key="MS_WebHookReceiverSecret_Custom" value="123456789012, 1=9876543210987"/>
```

If you do the second, `123456789012` is the secret key to use with the URL `https://{host}/api/webhooks/incoming/custom` and `9876543210987` is for `https://{host}/api/webhooks/incoming/custom/1`.

**Comment by dougbu** [comment]
Background: The last, optional portion of a WebHook URL is an id. That id is used to look up a specific secret key. For example, this allows use of one GitHub WebHook endpoint for multiple repos without sharing the same key with all of them.

**Comment by dougbu** [comment]
Believe all questions have been answered.

**Comment by abcplex** [comment]
Update: From WebHook Page https://webhooks.pbworks.com/w/page/13385124/FrontPage

"Simply provide your users with the ability to submit their own URL, and POST to that URL when something happens. It's that simple. There are no specs you have to follow."

I have created a simple Web APi project and it worked great. No need for WebHook project.
