### ISSUE TITLE
Blocking registration if the URI is not using secure transport

### ISSUE THREAD

**Issue by smanuel79** [aspnet/WebHooks#175]
Dear all,

This is not an issue and a request for information.
Currently the registration API accept web hook receiver URIs which can be either http or https. Is there any provision to only allow registration of https from the default implementation?

Thanks in advance,
Sujith

**Comment by dougbu** [comment]
If you're using the Microsoft.AspNet.WebHooks.Custom.Api package, the `WebHookRegistrationsController` doesn't expose anything simple. But, it should be possible to replicate MVC`s `[RequireHttps]` code in a Web API authentication filter. See https://github.com/aspnet/AspNetWebStack/blob/62d0b2df0bcca848a8e0848fd1866928df15528e/src/System.Web.Mvc/RequireHttpsAttribute.cs#L32-L58

**Comment by smanuel79** [comment]
Thanks a lot for the answer.
Yes, I am using Microsoft.AspNet.WebHooks.Custom.Api package. 
My question was more towards whether we can fail the webhook registration if the WebHookUri (as shown below ) attribute is having "http" and not "https".
 
API: /webhooks/registrations
Body:
{
    "WebHookUri": "<http uri>",
     "Filters": ["*"],
     "Secret": "<A secret key>",
     "Description": "<Description of the web hook>"
}

**Comment by dougbu** [comment]
> whether we can fail the webhook registration if the WebHookUri (as shown below ) attribute is having "http" and not "https"

Ah, different question than I answered 😺 

I recommend subclassing `WebHookManager`, overriding its `VerifyUri(...)`, and registering your new implementation in DI.

**Comment by smanuel79** [comment]
thanks a lot :-)
Let me do that.
