### ISSUE TITLE
Custom configuration for SqlStorage

### ISSUE THREAD

**Issue by Marusyk** [aspnet/WebHooks#191]
To better integration with existing project it would be great to have a more custom configurations. 

For now to store WebHook Registrations in SQL I need connection string in Web.config with name **MS_SqlStoreConnectionString**

```
 <add name="MS_SqlStoreConnectionString" connectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=Platform.Data;Integrated Security=True" providerName="System.Data.SqlClient" />
```

But I want to store WebHook Registrations in the same database that my application uses, so I already have connection string like:
```
 <add name="Platfom" connectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=Platform.Data;Integrated Security=True" providerName="System.Data.SqlClient" />
```
In this case I need to add two almost the same connection strings (only the name will be different)

Also, according to our sql conventions we shouldn't create a new Schema. 
I think, it would be nice to have custom configuration for that parameters (maybe the name of table too). And using it like:
```
config.InitializeCustomWebHooksSqlStorage(encryptData: true, connectionStringName: "Platform", schema: "plt", tableName:"CustomWebHooks");
```

What do you think about that? If ok, I could prepare a PR.

**Comment by dougbu** [comment]
The value of adding a new configuration value that only names another configuration value is not clear to me. Do you have any other use cases beyond not copying-and-pasting reused connection strings?

**Comment by Marusyk** [comment]
Yes, I need other schema name. Also connection string should be secure, and it is simpler to manage one string

**Comment by Marusyk** [comment]
@dougbu I'm sorry but I need to know what do you think about it. We need this feature and we with customers still waiting for your response. Can it be added to the next version (maybe with different implementation) or you can advise some other solution how to achieve our requirements? 
Thanks you in advance

**Comment by dougbu** [comment]
We've discussed and I will work with you on #192.

**Comment by dougbu** [comment]
6c173a343f

**Comment by dougbu** [comment]
Thanks very much @Marusyk ❕

**Comment by Marusyk** [comment]
Thank you for your time

**Comment by Marusyk** [comment]
Hello, are there any news about the future release of nuget?
