### ISSUE TITLE
Add PayPal sample to samples/ folder

### ISSUE THREAD

**Issue by Eilon** [aspnet/WebHooks#196]
There seem to be samples for just about everything, but not PayPal.

This should go here: https://github.com/aspnet/WebHooks/tree/dev/samples

**Comment by dougbu** [comment]
Other missing samples for ASP.NET WebHooks:
- Dynamics CRM
- Pusher
- Trello
- WordPress

**Comment by a-patel** [comment]
Other missing WebHooks:

- SendGrid
- Google APIs (if any)

**Comment by dougbu** [comment]
@a-patel this issue is about missing samples. All of the above ASP.NET WebHook receivers exist in the [aspnet/AspNetWebHooks](https://github.com/aspnet/AspNetWebHooks) repo.

I suggest filing separate issues for creating SendGrid and Google receivers. Choose the repo based on whether you want ASP.NET Core WebHooks receivers (this repo) or ASP.NET WebHooks receivers (aspnet/AspNetWebHooks).

**Comment by Pothulapati** [comment]
@dougbu  I would like to take this issue and will add samples for the following ASP.NET WebHooks.
- PayPal
- Trello
- WordPress
-  Pusher
- Dynamics CRM
Is that okay?

**Comment by Pothulapati** [comment]
@dougbu Looks like all the above-mentioned samples are done. Are there any other samples that I work on?

**Comment by Marusyk** [comment]
Hello @Pothulapati

Why do you think that all the above-mentioned samples are done? 
These samples for ASP.NET WebHooks are still missing:

Dynamics CRM
Pusher
Trello
WordPress

**Comment by Pothulapati** [comment]
@Marusyk Sorry, I mistook Asp.Net Core WebHooks for Asp.Net WebHooks. There is a  bit of confusion here as the naming is very similar. 
As the samples are for Asp.Net WebHooks should I mark an issue in that repository and start working on the samples?

**Comment by dougbu** [comment]
We haven't moved issues that no longer apply in this repo to [aspnet/AspNetWebHooks](https://github.com/aspnet/AspNetWebHooks). This is one that applies there but not here. See https://github.com/aspnet/AspNetWebHooks/tree/dev/samples

And, yes, @Pothulapati we will appreciate any samples you provide.

**Comment by dougbu** [comment]
Now that aspnet/AspNetWebHooks#14 is split from this issue, can close this when aspnet/AspNetWebHooks#4 is merged.

**Comment by dougbu** [comment]
aspnet/AspNetWebHooks@8024bbebc6
