### ISSUE TITLE
WebHook support for Zendesk

### ISSUE THREAD

**Issue by garora** [aspnet/WebHooks#2]
I received one request from one of readers of CodeProject - to add Webhook support for ``Zendesk`` here is the url [request Zendesk support](http://www.codeproject.com/Articles/1028439/Getting-Started-with-Microsoft-ASP-NET-WebHook-Pre?msg=5126263#xx5126263xx).

I am planning to make a pull request for the same. Just a question is it planned or not @HenrikFrystykNielsen @shanselman @halter73 . If you guys have already planned to push this webhook then its not good to make a duplicate pull request.

**Comment by HenrikFrystykNielsen** [comment]
Hi Gaurav,

Thanks for asking -- we don't have this planned at the moment so any help would be greatly appreciated!

Henrik

**Comment by garora** [comment]
@HenrikFrystykNielsen -I will be glad to make a pull request. I created one pull request for BitBucket - which is not yet completed just to initiate the things. I would appreciate if you take a look and merge down to your development branch for future releases, I will make more changes for BitBucket webhook. I will be honored to be a part of this great open source repository :100:

**Comment by HenrikFrystykNielsen** [comment]
@garora -- thank you so much for your PR for BitBucket. I'll have a look in the next day or two!

Thanks!

Henrik

**Comment by garora** [comment]
Thanks a ton. @Henrik just a note this is not complete code plz review and
if you find it good plz merge in your dev branch and I will complete it in
next PR.

Also I will be making a new PR for Zendesk.

**Comment by henrik** [comment]
Wrong Henrik. Unsubscribing.

**Comment by garora** [comment]
@HenrikFrystykNielsen - Initiated and made a [PR](https://github.com/aspnet/WebHooks/pull/9) for Zendesk WebHooks for your review.

**Comment by garora** [comment]
@HenrikFrystykNielsen - Couple of webhooks in my roadmap, I would only be able to push, once current  [PR](https://github.com/aspnet/WebHooks/pull/9) for Zendesk WebHooks get approved!

**Comment by HenrikFrystykNielsen** [comment]
@garora sounds good -- could you please send me an actual Zendesk webhook (including headers etc.) so that I can use it for validation? Getting it using something like http://requestb.in/ would be greatly appreciated!

**Comment by garora** [comment]
My demo account has been expired so, I do not have actual values.
You can use sample data mentioned in documentations.

**Comment by HenrikFrystykNielsen** [comment]
Thanks but I am looking for the full HTTP request so that I can validate that. I have tried many different things but so far I haven't been able to get an actual event posted. Any help would be much appreciated!

**Comment by garora** [comment]
Sure, allow me few hours. I will send you few samples.

**Comment by garora** [comment]
@HenrikFrystykNielsen - I apologize for delayed response. Here is everything: [your_push_notification_payload](https://developer.zendesk.com/embeddables/docs/android/push_notifications_webhook#server-integration).

We can also use [Getting with Triggers](https://developer.zendesk.com/rest_api/docs/core/triggers#getting-triggers) in case Zendesk admin configured ```triggers```

Here is the sample result for: `GET /api/v2/triggers/{id}.json`

`{
  "trigger": {
    "id": 1,
    "title": "Implementing WebHooks using Asp.Net",
    "raw_title": "{{dc.webhooks_using_asp_net}}"
    "active": true,
    "conditions": [ ... ],
    "actions": [ ... ],
    "updated_at": "2015-09-10T22:50:26Z",
    "created_at": "2015-09-18T22:50:26Z"
  }
}`

Here are few demo app from @Zendesk team [Demo apps](https://github.com/zendesk/demo_apps).

I hope its helpful.

**Comment by HenrikFrystykNielsen** [comment]
Thanks for the PR! It's now in dev branch: 1a213d7b9c95086ed0820942abb9ff6cf1488e0e. Release should be out in a few days.
