### ISSUE TITLE
Salesforce https requirement

### ISSUE THREAD

**Issue by supergibbs** [aspnet/WebHooks#20]
On our network, we use a secure connection to the the our external proxy which relays the message to our internal IIS servers over http. This causes the Salesforce WebHookReceiver to complain. Can we have an option to disable that requirement?

**Comment by HenrikFrystykNielsen** [comment]
That's a good scenario -- yes, that makes sense.

**Comment by HenrikFrystykNielsen** [comment]
I have committed this fix to dev branch: a47d684ab5a241f9904bfb77fd5786ae1f4571a5 It will go out with the next nugget drop.

**Comment by supergibbs** [comment]
Awesome, thanks!
