### ISSUE TITLE
AmazonS3/Minio WebHook

### ISSUE THREAD

**Issue by MontyGvMC** [aspnet/WebHooks#202]
Your great samples provide a big list of services.

AmazonS3 and Minio are missing though.

Mind adding them?

Spec of Amazon S3 structure
http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html

A (closed) issue on the minio github repository:  https://github.com/minio/minio/issues/5204

**Comment by danroth27** [comment]
No plans for this receiver at this time. If someone else wants to implement this receiver though we'd be happy to link to it.
