### ISSUE TITLE
Add support for instantiating handlers via DI

### ISSUE THREAD

**Issue by mteper** [aspnet/WebHooks#22]
Inability to have a webhook receiver handler be resolved via DI is a pain. Given the work put into finding and instantiating handlers via reflection that is already in place, I am wondering whether the DI path was intentionally left out?

**Comment by HenrikFrystykNielsen** [comment]
DI is very much supported. In fact, all of WebHooks extensions (handlers, receivers, and a bunch more) are wired up so that it first look in DI and only if nothing is there does it fall back on it's default behavior. That is, if you register DI with WebApi and register your handlers with that then they should get picked up by your DI.

**Comment by mteper** [comment]
Tried that, but the handler was not being pulled from DI, and instead I got the following exception: `WebHook receiver 'stripe' could not process WebHook due to error: No parameterless constructor defined for this object.`

Your note made me persist a bit further, and once I explicitly registered the handler as `IWebHookHandler` things fell into place.

Thanks!

**Comment by andysinclair** [comment]
Sorry to reply to a closed issue but I am having the same problem.
Can either of you send me some code to give me an idea of how to get DI working with webhooks? I am using Autofac and have tried variations of:

`builder.RegisterInstance(stripeWebHookHandler).As<IWebHookHandler>().SingleInstance();`
`builder.RegisterApiControllers(typeof (StripeWebHookHandler).Assembly).As<IWebHookHandler>();`

etc. to no avail. Any pointers would be greatly appreciated,
Thanks!

**Comment by mteper** [comment]
I have

```cs
// Register Stripe webhook
builder.RegisterType<StripeHandler>().As<IWebHookHandler>();

// Register Web API controllers.
builder.RegisterApiControllers(Assembly.GetExecutingAssembly());
```

**Comment by andysinclair** [comment]
Thank @mteper all working as expected now.

**Comment by HenrikFrystykNielsen** [comment]
yes, that looks fine. It is up to you whether you want the handler to be a singleton or created on every invocation. If you want it as a singleton then add .AsSingleton() to the call above.

**Comment by cwoolumtechnossus** [comment]
I'm having a similar issue with Autofac. I'm getting the error 

> Scope with a Tag matching 'AutofacWebRequest' is visible from the scope in which the instance was requested. This generally indicates that a component registered as per-HTTP request is being requested by a SingleInstance() component (or a similar scenario.) Under the web integration always request dependencies from the DependencyResolver.Current or ILifetimeScopeProvider.RequestLifetime, never from the container itself.

My registration looks like 

``` 
builder.RegisterType<AccountsWebhookHandler>().As<IWebHookHandler>();
```

I've tried registering it as ```InstancePerRequest()``` as well

**Comment by HenrikFrystykNielsen** [comment]
Could I get you try and add ".SingleInstance()" to the registration?

**Comment by cwoolumtechnossus** [comment]
I'm getting the same error

**Comment by cwoolumtechnossus** [comment]
Based on Option 1 on [this page](http://docs.autofac.org/en/latest/faq/per-request-scope.html#sharing-dependencies), I converted all my dependencies to use instance per lifetime scope and the web hook now works. It says that it should be effectively the same thing but I'll need to test to confirm.

**Comment by HenrikFrystykNielsen** [comment]
Thanks for trying this out. At the moment the handlers are single instance but it would be good to see if we can make that more flexible. I may not get to this until later this week though.

**Comment by jakenuts** [comment]
Second on making handlers lifetime configurable. The majority of the services my Webhook would integrate with internally are per-request which makes them more-or-less off limits to a singleton handler.

**Comment by cwoolum** [comment]
Funny this was just brought up again because I was just working on it. I think I've found a workaround that allows instance per request dependencies to be used. ```ExecuteAsync``` is fired on a per request basis. You can manually create the AutofacWebRequest lifetime scope when that is called and fetch your dependencies in that scope. It's working in my local tests and I'm about to deploy and test IRL. Here's the code I'm using:

```
public class StripeWebHookHandler : WebHookHandler
{       
        private ILifetimeScope _lifetimeScope;        

        public StripeWebHookHandler(ILifetimeScope lifetimeScope)
        {
            this.Receiver = StripeWebHookReceiver.ReceiverName;
            _lifetimeScope = lifetimeScope;
        }

        public override async Task ExecuteAsync(string generator, WebHookHandlerContext context)
        {
            // Create our fake request scope
            using(var scope = _lifetimeScope.BeginLifetimeScope("AutofacWebRequest"))
            {
                var someDependency = scope.Resolve<IServiceYouWant>();

                // Process your message as usual

            }         
         }
}

**Comment by cwoolum** [comment]
I've made changes to the above. You cannot put the scope in a using statement or it closes the scope for all  lifetimes.

**Comment by HenrikFrystykNielsen** [comment]
The sample [1] does use per-instance handlers (and now with a per-instance ctor dependency). That should not require any lifetime scopes as far as I can see.

Hope this helps!

Henrik

[1] https://github.com/aspnet/WebHooks/blob/master/samples/GenericReceivers.DependencyInjection/WebHooks/GenericJsonWebHookHandler.cs
