### ISSUE TITLE
Handler not being reached. 

### ISSUE THREAD

**Issue by abarrafo** [aspnet/WebHooks#23]
Hi, I am running a MVC 5 project with target framework = 4.5.2. From nuget I installed Microsoft.AspNet.Webhooks.Receivers.GitHub. I then implemented the WebApiConfig.cs and GitHubHandler.cs following the documentation. I am getting a response 200 back so it seems authentication is occurring and a response is happening except I am unable to reach the handler. 

        public class GitHubHandler : WebHookHandler
    {
        public GitHubHandler()
        {
            this.Receiver = "GitHub";
            this.Order = 1;
        }

        public override Task ExecuteAsync(string receiver, WebHookHandlerContext context)
        {
            string action = context.Actions.First();
            JObject data = context.GetDataOrDefault<JObject>();

            return Task.FromResult(true);
        }
    }

Is it required that I also install the AspNet WebApi package? Version? When I do install the latest WebApi package I get reference problems to System.web.http

**Comment by garora** [comment]
@abarrafo - I tried with latest version of and I did not encounter any exception. Your code looks fine. I suggest take a look here [GitHub WebHooks](http://blogs.msdn.com/b/webdev/archive/2015/09/04/introducing-microsoft-asp-net-webhooks-preview.aspx). Also, on this repository there are ```Samples``` available you can also refer these samples.

**Comment by abarrafo** [comment]
I don't encounter any exceptions either. The output is as follows when the webhook comes in: 

    w3wp.exe Information: 0 : Registered 'IWebHookReceiver' instances with the following names: stripe, github.
    w3wp.exe Information: 0 : Processing incoming WebHook request with receiver 'GitHub' and id ''.
    w3wp.exe Information: 0 : Registered configuration setting 'GitHub' for ID '''.   

Authentication is occurring and a response of 200 is being returned to GitHub, Yet my Handler is never called, so I am not able to do any processing on the incoming webhook.

**Comment by abarrafo** [comment]
Thanks. This is a non-issue. It works great. I found my error: 

                // If this is a ping request then just return. Otherwise call handlers.
                if (string.Equals(actions.FirstOrDefault(), PingEvent, StringComparison.OrdinalIgnoreCase))
                {
                    return request.CreateResponse();
                }

Looking through your work I realized that I was just sending ping requests and this code snippet says it all.
