### ISSUE TITLE
Custom Receiver

### ISSUE THREAD

**Issue by Havret** [aspnet/WebHooks#238]
Are there any plans to implement Custom Receiver compatible with the [Custom Sender](https://github.com/aspnet/AspNetWebHooks/tree/dev/src/Microsoft.AspNet.WebHooks.Custom) from aspnetwebhooks project?

**Comment by dougbu** [comment]
@Havret the Custom receiver is part of #182 and the sender is part of #183.

Thank you for your feedback. We're closing this issue as the questions asked here have been answered and the requested features are covered in other issues.
