### ISSUE TITLE
Add `ModelStateInvalidFilter` to actions with an applied `WebHookAttribute`

### ISSUE THREAD

**Issue by dougbu** [aspnet/WebHooks#240]
We should get rid of the `if (!ModelState.IsValid)`&hellip; boiler-plate in user code.

Should also `throw` an `InvalidOperationException` if `[ApiController]` is applied to a controller containing WebHook actions.

/cc @rynowak anything else we need to worry about now that WebHooks gets all the 2.1 goodness?

**Comment by dougbu** [comment]
More code we can clean up using 2.1 features: Don't need to special-case media type suffix matches and should instead use `application/*+json` or `application/*+xml` in `WebHookVerifyBodyTypeFilter`. The following hack can go away: https://github.com/aspnet/WebHooks/blob/ca7f0e7c9a11663be336d0d0412e0e26b4d9117a/src/Microsoft.AspNetCore.WebHooks.Receivers/Filters/WebHookVerifyBodyTypeFilter.cs#L167-L171

**Comment by mkArtakMSFT** [comment]
@danroth27, any objections about moving this out from preview2?

**Comment by dougbu** [comment]
ec834ebabb

**Comment by dougbu** [comment]
Merged to `dev` in 607d59b9e6
