### ISSUE TITLE
Generic receiver sample wrong app setting

### ISSUE THREAD

**Issue by mikanyg** [aspnet/WebHooks#25]
Fiddled around with the Generic receiver sample, and was unable to get it to work, untill I found that the appsettings was named wrong for the sample. The key found in https://github.com/aspnet/WebHooks/blob/master/samples/GenericReceivers/Web.config
is called:
MS_WebHookReceiverSecret_Custom 

but should be called 
MS_WebHookReceiverSecret_GenericJson

**Comment by HenrikFrystykNielsen** [comment]
right - thanks! I will have a blog out on how to use this in a few days (hopefully)
