### ISSUE TITLE
Concrete Event Classes

### ISSUE THREAD

**Issue by Korporal** [aspnet/WebHooks#252]
Are there any plans for representing each of the (e.g. GitHub) event payloads as distinct concrete classes?

Perhaps these could even be defined as event classes and the event pattern/conventions followed?

Thoughts?

**Comment by dougbu** [comment]
We have no such plans. Part of the reason is the incredibly large schema for some receivers e.g. GitHub. Few applications need more than a few of the properties sent.

**Comment by Korporal** [comment]
@dougbu - Hi,

Well although there are a lot of payload types there are utilities like [this one](https://jsonutils.com/). Also this project has over 280 forks so over time - once a pattern has been established in the solution - for developers to gradually add payloads on an as needed basis.

I'd be happy to get this going if you're prepared to see pull requests for this?

**Comment by dougbu** [comment]
I doubt we would accept PRs for concrete types for GitHub payloads. The additional code would need to be tested and maintained but has minimal value.

Again, few applications need more than a few of the properties sent. Much better to use Json.NET to extract the values of interest, especially now that C# has null-conditional aka safe navigation operators (`?.` and `?[]`).
