### ISSUE TITLE
Support custom Actions after launching a WebHook fails or succeeds

### ISSUE THREAD

**Issue by thomeval** [aspnet/WebHooks#26]
`WebHookManager.cs` has an internal constructor that allows custom Actions to be defined whenever a WebHook is successfully launched or not.  Unfortunately, it is noted in the documentation that *"This constructor is intended for unit testing purposes."*, and there is currently no practical way to make use of this functionality.

Would you please consider implementing a public constructor with `onWebHookSuccess` and `onWebHookFailure` parameters, or providing this functionality in another way?

**Comment by HenrikFrystykNielsen** [comment]
There now is a mechanism for sending notifications to all users and when doing so you can pass in a predicate which can filter which webhooks should fire. Check it out in dev branch: 6523bb08c502eaef2bc6fe5b88219b4740eaa552
