### ISSUE TITLE
No connection string named 'MS_SqlStoreConnectionString' could be found in the application config file.

### ISSUE THREAD

**Issue by vindberg** [aspnet/WebHooks#27]
Hi, I have multiple migration configurations in my project and have moved Webhooks to a webhookconfiguration folder.

Im getting the above error when calling this:
```Add-Migration -Name InitialWebhooks -ConfigurationTypeName MyCompany.Web.Migrations.WebhookConfiguration.Configuration -ConnectionStringName MS_SqlStoreConnectionString```

This is my connectionstring:
```
<connectionStrings>
	  <add name="MS_SqlStoreConnectionString" connectionString="Data Source=.\dev;Initial Catalog=MyCompany;Integrated Security=True" providerName="System.Data.SqlClient" />
  </connectionStrings>
```

Any ideas?

Thanks.

**Comment by HenrikFrystykNielsen** [comment]
In the Nuget Packet Manager Console, have you set the default project to where you have your web.config file containing the connection string? You can see [1] for details.

Henrik

[1] http://blogs.msdn.com/b/webdev/archive/2015/11/07/updates-to-microsoft-asp-net-webhooks-preview.aspx

**Comment by vindberg** [comment]
Yes, default project is set to MyCompany.Web. Also here are my configuration class:
```
internal sealed class Configuration : DbMigrationsConfiguration<Microsoft.AspNet.WebHooks.WebHookStoreContext>
{
    public Configuration()
    {
        AutomaticMigrationsEnabled = false;
		MigrationsDirectory = @"Migrations\WebhookConfiguration";
	}
}
```
I also tried removing my other connection strings in webconfig with no luck. Im running .Net 4.6 if that helps anyway :)

**Comment by HenrikFrystykNielsen** [comment]
Have you tried running the migration command with verbose output? Does that indicate what may be the error?

**Comment by vindberg** [comment]
Thanks. My solution startup project was not set to the web project. So the Nuget Packet Manager Console was looking in the Startup project even though the Default project: was correctly defined. Strange.

Its working now, thanks.
