### ISSUE TITLE
Any custom receiver examples?

### ISSUE THREAD

**Issue by codermrrob** [aspnet/WebHooks#274]
Great work, it is coming to fruition just as we need to build .Net Core Webhook receivers. I need to build custom receivers for a variety of systems not covered in the out-of-the box receivers. Can you point me at an example for custom receiver development. I've been searching around for a day or two but not finding anything. Thanks.

**Comment by WestDiscGolf** [comment]
@codermrrob I am currently working on a fitbit one which, once this library stablises and generates a nuget pacakge, I will be publishing in it's own repository and packaging to nuget etc. 

However until that point I have found that it's easier to develop it in the WebHooks solution as it gets the latest package references and you can debug into the library easily. 

If you want to take a look my current development as an example can be found in https://github.com/WestDiscGolf/WebHooks/tree/fitbit

Hope it helps!

**Comment by codermrrob** [comment]
thanks... I had just realized the same, that better to develop it in the WebHooks solution. Cheers for your fitbit link.
