### ISSUE TITLE
Latest commit has broken at least the Github and Azure Alert examples

### ISSUE THREAD

**Issue by WestDiscGolf** [aspnet/WebHooks#275]
On running the latest dev branch in the repo I now get the following error when running the Github and and Azure Alert example projects.

![image](https://user-images.githubusercontent.com/374343/38705625-13ca7dd4-3ea2-11e8-9b38-fb6276f700e4.png)

I thought it was just mine when I merged in the latest changes but unfortunately not :-(

**Comment by dougbu** [comment]
Yup, I left a bit out of #258 / c9ab0b4ede. Fix is already out for review, see #277.

**Comment by WestDiscGolf** [comment]
Cool, thanks! I've merged it in before it made the main branch so I can continue. Will let you know how it goes :-)

**Comment by dougbu** [comment]
- eecaac30c5 in `release/2.1`
- fd964d12a9 merged that into `dev`
