### ISSUE TITLE
Webhooks support for AWS SNS messages

### ISSUE THREAD

**Issue by mteper** [aspnet/WebHooks#28]
See http://blogs.aws.amazon.com/php/post/Tx2G9D94IE6KPAY/Receiving-Amazon-SNS-Messages-in-PHP for example of how to handle (example describes PHP but should be pretty straight-forward).

**Comment by aspnet-hello** [comment]
This issue was copied to aspnet/AspNetWebHooks#16

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspLabs#55
