### ISSUE TITLE
Please add support for the Vend API

### ISSUE THREAD

**Issue by Yusha813** [aspnet/WebHooks#289]
Hello, I am trying to use the WebHooks feature to receive posts from the [Vend API](https://docs.vendhq.com/docs/webhooks). Please add a NuGet package for this.

**Comment by dougbu** [comment]
@Yusha813 we've moved this issue is in the Backlog milestone. This means that it is not going to happen for the coming release. We will review the backlog and consider this ask in the future.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspLabs#41
