### ISSUE TITLE
Decouple sending WebHooks from the user

### ISSUE THREAD

**Issue by Suchiman** [aspnet/WebHooks#29]
http://blogs.msdn.com/b/webdev/archive/2015/09/15/sending-webhooks-with-asp-net-webhooks-preview.aspx
> Note that we only want WebHooks to be sent to the current user. That is, we don’t want user A’s events going to user B and vice versa. This means that to generate an event we must have a valid user ID. In the case of the controllers we do this by ensuring that the user is authenticated using the [Authorize] attribute.

There are certainly use cases where this coupling makes sense but i think it does not in most cases.

Simplest example would be posting a PR to this repo. It would trigger a webhook which sends a notification to the `dnfclas` bot to check wether the CLA is already signed. The current implementation would only allow to send this webhook to myself in case i've registered a WebHook here.

I've currently work arounded this for me by getting the `IWebHookManager` from DI and using the `NotifyAsync` methods which allows passing a userId. I then use `"*"` as `user` which is special cased in my `EFWebHookStore` to just return all WebHooks independently from the user which works... but you know, this is fairly not how it's supposed to be done.

It would greatly enhance the usefulness if this use case is respected in its design.

**Comment by HenrikFrystykNielsen** [comment]
Good point -- and support is now added :) Check it out in dev branch: 6523bb08c502eaef2bc6fe5b88219b4740eaa552

**Comment by Suchiman** [comment]
Thanks, looks good :+1:
