### ISSUE TITLE
ASP.NET Core WebHooks moved out of ASP.NET Core 2.1

### ISSUE THREAD

**Issue by danroth27** [aspnet/WebHooks#296]
Discussion for https://github.com/aspnet/Announcements/issues/299

------

We are moving ASP.NET Core WebHooks out of the ASP.NET Core 2.1 to give more time to validate the design and implementation. We will continue to ship previews ASP.NET Core WebHooks packages, but they not ship as stable packages as part of the ASP.NET Core 2.1 release.

### Why?

[ASP.NET Core WebHooks](https://github.com/aspnet/webhooks) is only a partial port of [ASP.NET WebHooks](https://github.com/aspnet/aspnetwebhooks) and hasn't received sufficient attention during the ASP.NET Core 2.1 release for us to feel comfortable shipping it at this time.

**Comment by WestDiscGolf** [comment]
Thanks for the update @danroth27. I can't deny I'm a little disappointed to hear this but completely understand the reasoning. It's better to have good quality than ship something early and not be happy with it :-)

I have been working on [my own webhook](https://github.com/WestDiscGolf/Fitbit.Net-Webhook) which I will update with the latest preview packages as they come.

Will there be opportunity for more community contributions to the webhook library now it's not on the 2.1 train?

Cheers

**Comment by tpeczek** [comment]
Is there a plan to make 1.0.0-preview3-final available on NuGet? Currently it's only on MyGet.

**Comment by WestDiscGolf** [comment]
@tpeczek none of the others, AFAIK, have been put on nuget so doubt it. I had to add the myget feed for my Webhook. Hoping more info in the 2.2 time frame will come out soon :-)

**Comment by tpeczek** [comment]
@WestDiscGolf 1.0.0-preview1-final and 1.0.0-preview2-final are on NuGet and you can use them. I'm also using MyGet rigth now, but with ASP.NET Core 2.1.0 RTM out I was hoping to switch my project back to NuGet. The only thing stopping me is absence of 1.0.0-preview3-final.

**Comment by WestDiscGolf** [comment]
@tpeczek ah cool. Dont think I realised. When it was dropped from the 2.1 timeframe other stuff, both tech and personal, got in the way. Hope to pick it back up again once more info on 2.2 is released.

**Comment by WestDiscGolf** [comment]
@tpeczek Just checked and 1.0.0-preview3-final isn't on myget anymore :-(

@danroth27 / @dougbu Any update on 1.0.0-preview3-final on nuget?

**Comment by tpeczek** [comment]
@WestDiscGolf It looks like it's still there: https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.AspNetCore.WebHooks.Receivers/1.0.0-preview3-final

**Comment by WestDiscGolf** [comment]
@tpeczek Thanks for that. I thought I'd tried that but must have missed typed it :-)

**Comment by vankampenp** [comment]
What is the best place to discuss the functionality of webhooks in 2.x?
I am missing a way to create a custom webhook, or at least lack the understanding how to do that :-)
There were two webhook consumers that I would like to integrate, but each are different from the once that are provided. For example WooCommerce on Wordpress uses JSON, so it is not compatible with the Wordpress webhook.

**Comment by tpeczek** [comment]
@vankampenp 

If what you are really looking for is creating your own custom webhook receiver you may find my blog series useful: [Under the hood of ASP.NET Core WebHooks](https://www.tpeczek.com/2018/05/under-hood-of-aspnet-core-webhooks.html)

You may also want to take a look at coupel early custom receivers implementations:
- [Fitbit.Net-Webhook](https://github.com/WestDiscGolf/Fitbit.Net-Webhook)
- [WebSub.NET](https://github.com/tpeczek/WebSub.NET/tree/master/src/WebSub.AspNetCore.WebHooks.Receivers.Subscriber)

**Comment by WestDiscGolf** [comment]
@vankampenp I documented my investigation of the the early webhooks and writing the fitbit one. Check out [my blog series](https://adamstorr.azurewebsites.net/blog/aspnetcore-webhooks-mini-series). Hope this helps.

**Comment by vankampenp** [comment]
@tpeczek and @WestDiscGolf, thanks these are useful. I had hoped to get an example that shows how to override some methods to allow you to customize the webhook, rather than changing the available source. But maybe this is the root. I will post an issue.

**Comment by lsuarez5280** [comment]
Since this is also going to miss the 2.2 milestone, do we know where this is going to fall on the roadmap? This is seconds from being pushed over the finish line and I'd like to update our existing Framework-based webhook receivers to this library.

**Comment by Eilon** [comment]
@danroth27 / @DamianEdwards - do we have an updated roadmap for this?

**Comment by WestDiscGolf** [comment]
I can't help but feel this is going to wait for the new fully opened End Point Routing middleware coming in v3. I just feel like with the clashing of the apicontroller attribute work and the hard coded routing in the webhooks it makes sense that it will use the new middleware when it arrives

**Comment by usaadi** [comment]
Is there an available preview for custom webhook sender on myget or elsewhere?

**Comment by dougbu** [comment]
@usaadi not something built in this repo. Others may certainly have forked the code and implemented sender support.

If you want sender support in general, the other option is to use Microsoft.AspNet.WebHooks.Custom and related packages. Those are available on NuGet.org. Slightly newer versions are available in the https://dotnet.myget.org/gallery/aspnetwebhooks feed.

**Comment by SeanFarrow** [comment]
Given that this project has been moved to asplabs, where should we raise issues/questions?

**Comment by WestDiscGolf** [comment]
Moving to asplabs is both disappointing and confusing :-(

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspLabs#38

**Comment by Eilon** [comment]
ASP.NET WebHooks issues (as well as this issue 😄 ) have moved to https://github.com/aspnet/AspLabs.
