### ISSUE TITLE
Move version back to 1.0.0-preview3

### ISSUE THREAD

**Issue by dougbu** [aspnet/WebHooks#297]

**Comment by dougbu** [comment]
@mkArtakMSFT to avoid pushing newer-looking packages to https://dotnet.myget.org/gallery/aspnetcore-dev, this needs to go into the `release/2.1` branch.

**Comment by mkArtakMSFT** [comment]
I'm removing the "SHP: Approval pending" label as we've already agreed that this is not going to ship as part of 2.1.0 release.

**Comment by dougbu** [comment]
0f7a7c73df

**Comment by dougbu** [comment]
Cherry-picked change into `release/2.1` as 5815691af6
