### ISSUE TITLE
Will WebHooks.Receivers.VSTS be ported to .NET Core / .NET Standard 2.0?

### ISSUE THREAD

**Issue by NenoLoje** [aspnet/WebHooks#305]
Are there plans to port the [VSTS receiver](https://github.com/aspnet/AspNetWebHooks/tree/dev/src/Microsoft.AspNet.WebHooks.Receivers.VSTS) from the old repo ([AspNetWebHooks](https://github.com/aspnet/AspNetWebHooks)) to this one ([WebHooks](https://github.com/aspnet/WebHooks))?

Thanks,
--Neno

**Comment by dougbu** [comment]
We have no such plans to support the VSTS receiver at this time.
