### ISSUE TITLE
Add support for user-specified route template

### ISSUE THREAD

**Issue by robertmiles3** [aspnet/WebHooks#307]
For OCD-ish people like myself, I'd love to be able to change the route template. I already have "api" in my subdomain, so it's a bummer to also see it in the path (ie: `/api/webhooks/incoming`) as well.

I see from [here](https://github.com/aspnet/WebHooks/blob/13da6ec8ac8bab0b4fc7389dcc9352a4855cf8aa/src/Microsoft.AspNetCore.WebHooks.Receivers/ApplicationModels/WebHookSelectorModelProvider.cs#L146-L153) that it is currently hard-coded given "no requirement for user-specified route templates".

Is this a feature that could be added? Maybe something like...

```c#
services.AddMvc()
    .AddWebHooks(options =>
    {
        options.RouteTemplate = "/webhooks/incoming/";
    })
    .AddGitHubWebHooks();
```

**Comment by dougbu** [comment]
We have no plans to implement this feature at this time. If our priorities change in the future, we may reconsider.
