### ISSUE TITLE
Validation requests should log a message indicating that they were processed

### ISSUE THREAD

**Issue by HenrikFrystykNielsen** [aspnet/WebHooks#31]
For example, Stripe receiver should log that it received a test event ID request.

**Comment by codputer** [comment]
Thanks again for your help on this - the filter on event id evt_000000000000  I believe I understand.  However, via the Stripe testing interface, this is only event that is published in a testing role.  If I want to test my processing logic for  Charged Successful event, the event ID that is produced is still evt_0000000.  As I'm new to the Stripe API, perhaps it's my understanding, but with this filter the only way to test any event via the Stripe testing interface is actual Live events.  That doesn't seem to be the best use of their testing tool, and dramatically reduces the usefulness of the Slack webhook.  Would it not be better to have a parameter to manage this filter by a config option, or perhaps by the fact the project is in DEBUG mode?

**Comment by codputer** [comment]
Response from Stripe about evt id:

**Comment by HenrikFrystykNielsen** [comment]
Added messages -- see commit 43d7515608d0aff62431c6bf35febd9127a82774.
