### ISSUE TITLE
Microsoft.AspNetCore.WebHooks.Receivers.AzureContainerRegistry doens't open in Visual Studio 2017

### ISSUE THREAD

**Issue by davesmits** [aspnet/WebHooks#310]
I am trying to get everything running in VS2017 but when opening the solution it wants to migrate the Microsoft.AspNetCore.WebHooks.Receivers.AzureContainerRegistry. If I do this it's an empty project. 
I don't see anything weird inside the project file what can cause this and some help would be apricated!

As mentioned earlier I got a working port to core from the orginal webhook sender packages as they existed for the .Net Framework and was working on updating my fork to contain the latest changes from here

**Comment by dougbu** [comment]
@davesmits thanks for reporting this issue. Unfortunately, it does not reproduce for me.

In some cases, it's necessary to run at least the initial part of a command line build (`.\build.cmd /t:restore`) before opening Visual Studio. This ensures the correct SDK is available.

If that doesn't work, heed the warnings from `dotnet-install` at the top of the build's output about changing your `Path` environment variable.

Please let us know your success with the above suggestions.

**Comment by davesmits** [comment]
your first suggestion solved the issue
