### ISSUE TITLE
Flaky test: WebHookAction_NoEventHeader_IsNotFound

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/WebHooks#315]
This test [fails](http://aspnetci/viewLog.html?buildId=514940&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally with the following error:
```
Microsoft.AspNetCore.Routing.Matchers.AmbiguousMatchException : The request matched multiple endpoints. Matches: 
GitHubCoreReceiver.Controllers.GitHubController.HandlerForItsPushes (GitHubCoreReceiver)
GitHubCoreReceiver.Controllers.GitHubController.HandlerForIt (GitHubCoreReceiver)
GitHubCoreReceiver.Controllers.GitHubController.HandlerForPush (GitHubCoreReceiver)
GitHubCoreReceiver.Controllers.GitHubController.GitHubHandler (GitHubCoreReceiver)
GitHubCoreReceiver.Controllers.GitHubController.FallbackHandler (GitHubCoreReceiver)
   at Microsoft.AspNetCore.Routing.EndpointConstraints.EndpointConstraintEndpointSelector.SelectAsync(HttpContext httpContext, IEndpointFeature feature, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matchers.DfaMatcher.MatchAsync(HttpContext httpContext, IEndpointFeature feature)
   at Microsoft.AspNetCore.Routing.GlobalRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.CookieContainerHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.WebHooks.FunctionalTest.GitHubCoreReceiverTest.WebHookAction_NoEventHeader_IsNotFound() in /_/test/Microsoft.AspNetCore.WebHooks.FunctionalTest/GitHubCoreReceiverTest.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by ryanbrandenburg** [comment]
WebHookAction_NoEventHeader_IsNotFound [failed again](http://aspnetci/viewLog.html?buildId=514940&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=514945&buildTypeId=XPlat_Windows_Win8_Universe).

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=514893&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment]
WebHookAction_NoEventHeader_IsNotFound [failed again](http://aspnetci/viewLog.html?buildId=514895&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

**Comment by dougbu** [comment]
See #318 for product bug

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515163&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=514938&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Eilon** [comment]
@dougbu - please update the "TODO" items in the workflow to reflect the status.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515414&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515284&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515280&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NoEventHeader_IsNotFound [failed again](http://aspnetci/viewLog.html?buildId=515142&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515667&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NoEventHeader_IsNotFound [failed again](http://aspnetci/viewLog.html?buildId=515586&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by dougbu** [comment]
@rynowak much appreciated.

Is this `done`? And, should the workflow [above](https://github.com/aspnet/WebHooks/issues/315#issuecomment-407884752) be updated?
