### ISSUE TITLE
Flaky test: WebHookAction_NoUUID_IsBadRequest

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/WebHooks#317]
This test [fails](http://aspnetci/viewLog.html?buildId=514940&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally with the following error:
```
Microsoft.AspNetCore.Routing.Matchers.AmbiguousMatchException : The request matched multiple endpoints. Matches: 
BitbucketStronglyTypedCoreReceiver.Controllers.BitbucketController.BitbucketForIt (BitbucketStronglyTypedCoreReceiver)
BitbucketStronglyTypedCoreReceiver.Controllers.BitbucketController.BitbucketForPush (BitbucketStronglyTypedCoreReceiver)
BitbucketStronglyTypedCoreReceiver.Controllers.BitbucketController.Bitbucket (BitbucketStronglyTypedCoreReceiver)
   at Microsoft.AspNetCore.Routing.EndpointConstraints.EndpointConstraintEndpointSelector.SelectAsync(HttpContext httpContext, IEndpointFeature feature, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matchers.DfaMatcher.MatchAsync(HttpContext httpContext, IEndpointFeature feature)
   at Microsoft.AspNetCore.Routing.GlobalRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.CookieContainerHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.WebHooks.FunctionalTest.BitbucketStronglyTypedCoreReceiverTest.WebHookAction_NoUUID_IsBadRequest() in /_/test/Microsoft.AspNetCore.WebHooks.FunctionalTest/BitbucketStronglyTypedCoreReceiverTest.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by ryanbrandenburg** [comment]
WebHookAction_NoCode_IsBadRequest [failed again](http://aspnetci/viewLog.html?buildId=514940&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment]
WebHookAction_NoCode_IsBadRequest [failed again](http://aspnetci/viewLog.html?buildId=514945&buildTypeId=XPlat_Windows_Win8_Universe).

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=514893&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment]
WebHookAction_WithBody_Succeeds [failed again](http://aspnetci/viewLog.html?buildId=514895&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

**Comment by dougbu** [comment]
See #318 for product bug

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515163&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=514938&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NoEventHeader_IsNotFound [failed again](http://aspnetci/viewLog.html?buildId=515414&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515284&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515280&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515142&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NoEventHeader_IsNotFound [failed again](http://aspnetci/viewLog.html?buildId=515667&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515586&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NoUUID_IsBadRequest [failed again](http://aspnetci/viewLog.html?buildId=515731&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_NoCode_IsBadRequest [failed again](http://aspnetci/viewLog.html?buildId=515729&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_WithBody_Succeeds [failed again](http://aspnetci/viewLog.html?buildId=515716&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebHookAction_WithBody_Succeeds [failed again](http://aspnetci/viewLog.html?buildId=515720&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by dougbu** [comment]
@rynowak much appreciated.

Is this `done`? And, should the workflow [above](https://github.com/aspnet/WebHooks/issues/317#issuecomment-407884896) be updated?

**Comment by Eilon** [comment]
As long as the underlying issue was resolved, just closing is fine.
