### ISSUE TITLE
Need to either disable Global Routing or "onboard" this repo

### ISSUE THREAD

**Issue by dougbu** [aspnet/WebHooks#318]
Tests are failing due to `AmbiguousMatchException`s which likely relate to Global Routing. Tests are about to be disabled but we should fix the product code.

See #313 #314 #315 #316 #317

**Comment by dougbu** [comment]
Revert fad82fdb23 when this bug is fixed

**Comment by Eilon** [comment]
@dougbu do we know that it's a bug in WebHooks product code or could it be an issue in Global Routing? (cc @rynowak @JamesNK @kichalla )

**Comment by rynowak** [comment]
I've thought about this more, and I'm treating this as a bug in routing. Given our other discussions so far related to 2.2's routing features, I plan to make changes to MVC that will make webhooks 'just work'

**Comment by dougbu** [comment]
@rynowak should we close this issue (maybe label it `external`) and open something similar in aspnet/Routing? The new bug could link to aspnet/WebHooks@bedc118aef as a commit to revert when it's fixed.

**Comment by rynowak** [comment]
Sure, feel free to link to this one. https://github.com/aspnet/Routing/issues/630 I've added verifying that webhooks works with global routing to that issue's checklist.

**Comment by dougbu** [comment]
Closing as described above. aspnet/Routing#630 covers moving aspnet/WebHooks into the new world.
