### ISSUE TITLE
WebHooks receiver support for VSTS (Visual Studio Team Services) Service Hook

### ISSUE THREAD

**Issue by tanaka-takayoshi** [aspnet/WebHooks#32]
Do you have any plan for releasing VSTS Service Hook receiver?
https://www.visualstudio.com/integrate/get-started/service-hooks/events#build.complete

**Comment by jenyayel** [comment]
I have the same question. Although I managed to make an integration using `GenericJsonWebHookReceiver`, the payload has a complex structure which would be nice to map to strong types, similar to what was done in `InstagramWebHookReceiver`. Do you have plans or I can go ahead fork and implement?

**Comment by HenrikFrystykNielsen** [comment]
A PR would be greatly appreciated!

**Comment by jenyayel** [comment]
What is the preferred name for the project `Microsoft.AspNet.WebHooks.Receivers.TFS` or `Microsoft.AspNet.WebHooks.Receivers.VSTS`?

**Comment by HenrikFrystykNielsen** [comment]
I would say VSTS :)

**Comment by HenrikFrystykNielsen** [comment]
...and the nugets are out! Look for version rc1c

thanks for the pull request!
