### ISSUE TITLE
Change MvcOptions.EnableGlobalRouting to EnableEndpointRouting

### ISSUE THREAD

**Issue by JamesNK** [aspnet/WebHooks#321]
The EnableGlobalRouting property is being renamed! I have left the old property around to not break WebHooks during the transition.

When deps have updated I will send a webhooks PR to replace old and busted with new hotness.

**Comment by dougbu** [comment]
@JamesNK I believe this issue is no longer valid. @rynowak just checked in 216a4a7290 and that eliminated use of the `EnableGlobalRouting` property in this repo.

**Comment by rynowak** [comment]
Yep, nothing to do here.
