### ISSUE TITLE
TrimmingTokenizer.cs not available

### ISSUE THREAD

**Issue by forrestab** [aspnet/WebHooks#324]
I am creating a webhook receiver and need to verify the signature. I am following the slack signature verification filter, but it uses the `TrimmingTokenizer` class and that does not appear to be available in the latest `Microsoft.AspNetCore.WebHooks.Receivers` package. 

Is it in another package, am I missing something?

**Comment by dougbu** [comment]
We do not plan to make this utility generally available.

If you're creating your receiver in a fork of the aspnet/WebHooks repo, suggest doing as the Slack receiver does in its project file: https://github.com/aspnet/WebHooks/blob/9bdc69147f8a51b974bdd4179e47bc006e823d00/src/Microsoft.AspNetCore.WebHooks.Receivers.Slack/Microsoft.AspNetCore.WebHooks.Receivers.Slack.csproj#L8-L10

For receivers outside this repo i.e. not in a fork, feel free to use the `TrimmingTokenizer.cs` code in accordance with its license.

**Comment by dougbu** [comment]
> Is there any particular reason you all are not making it available?

@forrestab it's a low-level utility that we prefer not to expose from a WebHooks package; doesn't fit in the public API. We also had no call for this `struct` in other aspnet repos, which meant it was not a candidate for the Microsoft.Extensions.Primitives package. But, I'll ask around to see if your request is enough to reconsider including it there.

**Comment by dougbu** [comment]
@forrestab there's also proposals in dotnet/corefx which seem very similar to `TrimmingTokenizer` but the roadmap isn't clear. I [asked](https://github.com/dotnet/corefx/issues/26528#issuecomment-419506321) about the timeline in dotnet/corefx#26528.

**Comment by dougbu** [comment]
Closing given you can use the `TrimmingTokenizer` source until dotnet/corefx#26528 does the needful.

> For receivers outside this repo i.e. not in a fork, feel free to use the TrimmingTokenizer.cs code in accordance with its license.
