### ISSUE TITLE
Sending messages from web hooks on an load balacing setup

### ISSUE THREAD

**Issue by rajasekarshanmugam** [aspnet/WebHooks#33]
Hi,

Are there any recommendations or patterns for sending messages from an ASP.NET/IIS setup in a load balanced network that is using out of proc session state. Some of the implementations/deployments we have uses elasticity and hence runs on multiple nodes. If the processing happens "inproc" with no persistence, then the chance of ensuring guaranteed single-delivery is less. While storage model assumes subscriptions to be persisted, messages does not appear to be. Should this be handled externally or any recommendation/pattern exists?

**Comment by HenrikFrystykNielsen** [comment]
I am working on making it possible to persist sending messages as well by adding an abstraction on the sender side. It's a bit on the backburner due to other urgencies but  I hope to have it out soon.

**Comment by rajasekarshanmugam** [comment]
@HenrikFrystykNielsen, that's great to know. Looking forward for a drop to try it out.

**Comment by HenrikFrystykNielsen** [comment]
We have added support for scaling up and out, see commit 8c452662ec47fd72d0e80c83703b2493c87e5c45 and blog 'New Year Updates to ASP.NET WebHooks Preview' [1] for details

Henrik

[1] http://blogs.msdn.com/b/webdev/archive/2015/12/31/new-year-updates-to-asp-net-webhooks-preview.aspx

**Comment by rajasekarshanmugam** [comment]
@HenrikFrystykNielsen Wow, will be trying that ASAP. It is certainly a nice way to say happy new year.
