### ISSUE TITLE
Avoid having to know magic strings for Reciever names

### ISSUE THREAD

**Issue by drub0y** [aspnet/WebHooks#35]
Right now when creating a `WebHookHandler` the developer must configure what receiver you're interested in being tied to to via the `Receiver` property. This property is a string, which makes sense from an extensibility standpoint, but discovering what that value should be right now is a matter of documentation at best, but in reality it's actually reading source in GitHub right now. :smile:

Might I suggest a best practice pattern to establish would be for `IWebHookReceiver` implementations to expose a `public static readonly string ReceiverName` field? This would enable the developer to follow this simple pattern when writing `WebHookHandler`s:

```
public class MyFancyGithubWebHookHandler : WebHookHandler
{
     public MyFancyGithubWebHookHandler()
     {
          this.Receiver = GithubWebHookReceiver.ReceiverName
     }

     ....
}
```

FWIW, it looks like this is almost already established as a pattern, but the fields are currently `internal const` instead.

**Comment by drub0y** [comment]
Didn't want to muddy the waters of the original request, but an alternative might be to stop using strings altogether and instead acually link the handlers to the receivers more strongly via the actual `Type`. 

That would involve maybe changing the `IWebHookHandler::Receiver` property to type `Type` first. Then maybe make `WebHookHandler` into `WebHookHandler<T> where T : IWebHookReceiver`. So if you wanted to receive from `GithubWebHookHandler` then you'd do something like:
```
public class MyFancyGithubWebHookHandler : WebHookHandler<GitHubWebHookReceiver>
{
     ....
}
```

**Comment by HenrikFrystykNielsen** [comment]
I like the idea of making the binding easier. I still prefer to go with a string approach as types seem a bit heavy weight. Thanks for the suggestion!

**Comment by drub0y** [comment]
Sounds good and thanks for listening. Was just getting my feet wet with the framework and it was one of the first things I noticed wasn't obvious so I thought I'd call it out. Cheers!
