### ISSUE TITLE
Salesforce Webhook receiver forces Https. It should be optional.

### ISSUE THREAD

**Issue by AmbroiseCouissin** [aspnet/WebHooks#38]
Hi!

I am using a Load balancer that receives the wehook call (HTTPS). This load balancer redirects calls to machines that host the application HTTPS to HTTP (typical when using Elastic Beanstalk from AWS).

When I receive a webhooked message on my application, I get an error due to the fact I don't use HTTPS on my machine, but on the load balancer.

To avoid the problem, I have to reimplement the SalesforceWebhookReceiver at https://github.com/aspnet/WebHooks/blob/master/src/Microsoft.AspNet.WebHooks.Receivers.Salesforce/WebHooks/SalesforceSoapWebHookReceiver.cs and delete the line 
EnsureSecureConnection(request);

Don't you think it would be better to make HTTPS optional? It's not really the application's role to check if we are using HTTPS anyway no?

Thanks.

**Comment by HenrikFrystykNielsen** [comment]
You can use the existing setting called 'MS_WebHookDisableHttpsCheck' to control this, from [1]:

> Receivers Behind Firewalls
> 
> In certain cases, a WebHook receiver may sit behind a firewall or gateway that forwards requests as
> non-HTTPS requests, i.e. just as plain-text HTTP. In this case, the default WebHook receiver check
> that requires use of HTTPS will fail preventing the WebHook from being processed. This check can
> now be suppressed by setting the 'MS_WebHookDisableHttpsCheck' Application Setting to ‘true’. 
> That is, if ‘true’ this will cause regular HTTP requests to go through. Obviously this setting should be
> used with caution!

Hope this helps,

Henrik

[1] http://blogs.msdn.com/b/webdev/archive/2015/11/07/updates-to-microsoft-asp-net-webhooks-preview.aspx

**Comment by AmbroiseCouissin** [comment]
Thanks a lot! This is exactly what I'm looking for.
