### ISSUE TITLE
Alternative to application setting "MS_WebHookDisableHttpsCheck"

### ISSUE THREAD

**Issue by IanYates** [aspnet/WebHooks#39]
Hi.  I was inspired by #38 to write this and possibly submit a PR if it suits you.

It'd be nice if there was a way to disable the Https check from code rather than always going via appSettings.
Since it's a global setting there could be a public static method callable to disable Https checks plus a private static boolean indicating that the flag has been set.
Then it's just a matter of patching [line 164 of WebHookReceiver.cs](https://github.com/aspnet/WebHooks/blob/8c452662ec47fd72d0e80c83703b2493c87e5c45/src/Microsoft.AspNet.WebHooks.Receivers/WebHooks/WebHookReceiver.cs#L164) to check this flag too.

I'd be very happy to make the small PR.

I personally don't use this library yet but since I think I will in the near future, and I dislike having cryptic app settings, this would be useful for me.  I write commercial off-the-shelf software so I'm not always involved in the installation & configuration process, meaning a simple "disableHttps" appsetting flag that my own code interprets is better than having a flag for web hooks, a flag for my own code and perhaps a flag influencing some other third party library.

**Comment by IanYates** [comment]
If not acceptable then I guess I can at least hook in to the dependency resolver's `GetSettings()` call and have it check my own setting and pass through a dictionary with `MS_WebHookDisableHttpsCheck` set `true`

**Comment by HenrikFrystykNielsen** [comment]
Hi Ian,

Being able to control this from code makes a lot of sense. If you are up for it then a PR would be greatly appreciated :)

Henrik

**Comment by IanYates** [comment]
Great.  I'll put it together on the weekend :)

**Comment by HenrikFrystykNielsen** [comment]
Actually, the SettingsDictionary is just a dictionary so you can set values however you want. It just happens to initialize from the normal config settings, but you can set your own values however you want. You can get at the SettingDictionary from [1] -- just set MS_WebHookDisableHttpsCheck to true there.

Hope this helps,

Henrik

[1] https://github.com/aspnet/WebHooks/blob/master/src/Microsoft.AspNet.WebHooks.Common/Services/CommonServices.cs#L39
