### ISSUE TITLE
Allow any user to trigger an event?

### ISSUE THREAD

**Issue by vindberg** [aspnet/WebHooks#42]
Hi,

For a forum topic how can I use a webhook to update total number of replies. I need to register the event for all users? Or just register it as an client event.

P.S. I know it sound strange that the topic and replies are different services, but its just an example :+1:

**Comment by HenrikFrystykNielsen** [comment]
I am not sure I understand? Do you mean the total number of replies across all users? In that case the webhook would be more like an "admin" webhook that isn't specific to any user.

**Comment by vindberg** [comment]
Yes, exactly and "admin/system" webhook that isn't specific to any user. Any examples of that? Thanks.

**Comment by HenrikFrystykNielsen** [comment]
Hmm, not directly. I think the best way to accommodate this is to allow you to hook in to the webhook registration path and add whatever filters you want including broadcast filters so that you have a set of events that you can send to. That way it can be supported without the client having to do anything and you can send notifications to any event you create this way. Shouldn't take too long for us to come up with. Let me know what you think. Thoughts?

**Comment by HenrikFrystykNielsen** [comment]
This is now supported in commit a7e0496fa7f7343553829938abb496254c76545b -- you can now register an IWebHookRegistrar implementation which can add, modify, or reject a WebHook registration going through the WebHookRegistrationsController. This allows you to add filters can be used for broadcasting and group-casting.

**Comment by vindberg** [comment]
Thanks for such speedy response. I will have a look at your commit. Will you also be adding an example to the samples?

**Comment by HenrikFrystykNielsen** [comment]
I'll add it to the samples later but all you have to do really is provide a public, non-abstract implementation of the IWebRegistrar interface. That will ensure you get called as part of the registration process. You can then add a broadcast filter following the rules (either it be listed in an IWebHookFilterManager implementation or it is prefixed with "MS_Private_" to remain private for the server side). With the filter registered you can send notifications to all users having that filter using the usual NotifyAllAsync model described in [1].

Hope this helps,

Henrik
[1] https://blogs.msdn.microsoft.com/webdev/2015/12/31/new-year-updates-to-asp-net-webhooks-preview/
