### ISSUE TITLE
context.Id is blank on incoming slack webhooks and slashcommands

### ISSUE THREAD

**Issue by scoussens** [aspnet/WebHooks#50]
Using the examples and attempting others from scatch, all of the information comes in correctly, except that the context.Id is always blank so you can't filter based on that information.

**Comment by HenrikFrystykNielsen** [comment]
The 'id' value comes from the callback URI that you register with Slack like this:

https://<host>/api/webhooks/incoming/slack/{id}

For example, if you set 'id' to 'command1' then that will be the value when you receive WebHooks on that callback.

Hope this helps,

Henrik

**Comment by scoussens** [comment]
Perfect, thanks.
