### ISSUE TITLE
WebHookSender : logging retries / response code returned

### ISSUE THREAD

**Issue by paulduran** [aspnet/WebHooks#52]
We are looking at adding some structured 'audit' logging for our web hook sender so that we have a 'per customer' database of web hook 'events'.

Ideally , we would be able to record:

* for each retry
  * the time that we called the URL
  * the the response that we received
  * retry number
* whether it was ultimately successful or a failure

I think we can get the last item (whether it was success or failure) by overriding the OnWebHookFailure / OnWebHookSuccess methods.

Do you have any suggestions on how we can log 'audit events' in our database for the 'for each retry' events?

**Comment by HenrikFrystykNielsen** [comment]
Not without overriding a bunch of stuff but we can probably add a virtual OnWebHookRetry method and call that on retries.

**Comment by HenrikFrystykNielsen** [comment]
This is now in dev branch: 2d5c543d99e914c5f3f8558ace513bc81275195f Should make it to master in a few days.

**Comment by paulduran** [comment]
Thanks for your assistance there @HenrikFrystykNielsen . Is there a way to get any details of the 'previous' http request when we are retrying , or on success/failure .. such as the duration it took or the response code received?

**Comment by HenrikFrystykNielsen** [comment]
Nope :) If you want that level of detail then you'll have to either look at the logging output or wire it up yourself. We do log this information but it is more intended for diagnostics.
