### ISSUE TITLE
Documentation about sending webhooks and customizing it

### ISSUE THREAD

**Issue by muziekklas** [aspnet/WebHooks#55]
I am trying to use the framework, but I cannot find any information about how to modify the request body of the webhook request (sending to receivers).
http://docs.asp.net/projects/aspnetwebhooks/en/latest/sending/senders.html
The link on that doc is not really enough

**Comment by HenrikFrystykNielsen** [comment]
I just added a snippet to CustomSender sample project illustrating how you can customize the outgoing WebHook requests. Here's [1] an example of a custom WebHookSender and how to wire it up [2] in the configuration (see line 30). Of course you can also wire it up using a real DI engine -- that's up to you!

[1] https://github.com/aspnet/WebHooks/blob/dev/samples/CustomSender/WebHooks/MyWebHookSender.cs
[2] https://github.com/aspnet/WebHooks/blob/dev/samples/CustomSender/App_Start/WebApiConfig.cs

**Comment by muziekklas** [comment]
Wow! Thanks for the demo code and for the quick reply!!!
