### ISSUE TITLE
Unhandled exceptions in webhook handlers are not passed to IExceptionLogger

### ISSUE THREAD

**Issue by georgiosd** [aspnet/WebHooks#61]
Hi,

In normal Web API services, unhandled exceptions can be handled by registering an `IExceptionLogger`. However, this is not the case with webhook handlers - the exception seems to be swallowed. 

If hope this is a bug and not a feature! :)

**Comment by HenrikFrystykNielsen** [comment]
Interesting point -- at the moment, the exception is caught in the receiver controller -- it's the very last piece of [WebHookReceiversController](https://github.com/aspnet/WebHooks/blob/master/src/Microsoft.AspNet.WebHooks.Receivers/Controllers/WebHookReceiversController.cs).

I presume we can just let that bubble up instead.

**Comment by georgiosd** [comment]
Yes i think that would be best!

**Comment by HenrikFrystykNielsen** [comment]
ok, check this out: 2bc1d844a41e5ff353a9e4c9888ad936f572086e

**Comment by georgiosd** [comment]
Thank you sir :)
When can this go out to nuget?

**Comment by HenrikFrystykNielsen** [comment]
@georgiosd -- it's out -- look for rc1c :)

**Comment by georgiosd** [comment]
Thank you very much :)
