### ISSUE TITLE
Error when starting CustomSender sample project

### ISSUE THREAD

**Issue by remiplanglois** [aspnet/WebHooks#62]
Hi,
The error I get is: "Could not load file or assembly 'Microsoft.AspNet.WebHooks.Common' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key."

Any ideas? Should I configure something in Visual Studio?

Thanks in advance!

**Comment by HenrikFrystykNielsen** [comment]
Can you run build.cmd from the command line? That will fix it

**Comment by remiplanglois** [comment]
AzureStorageEmulator.exe was not installed.
Thanks!

**Comment by b4rj** [comment]
Hello, even tho I ran the build.cmd, I still got the same error.
Solved it by removing the "Microsoft.AspNet.WebHooks.Common" reference and installing it again using:

Install-Package Microsoft.AspNet.WebHooks.Common -Pre

**Comment by garora** [comment]
@b4rj - This would not work for me. I am trying to DEBUG my final changes for OneDrive. I followed your steps and now I am getting ```Microsoft.AspNet.WebHooks.Receivers.OneDrive```. In my case, I can't remove or add NugetPackage for OneDrive (because it does not exist). @HenrikFrystykNielsen - any suggestions?
