### ISSUE TITLE
Facebook Webhooks For Messenger Bot

### ISSUE THREAD

**Issue by BlueCity** [aspnet/WebHooks#64]
Hello, 
Firstly thanks for all these webhooks apis. But nowadays i am working on facebook messenger https://developers.facebook.com/docs/messenger-platform/webhook-reference but i can't find webhooks api for Facebook ? Will you publish api for facebook ? If yes when ? Thank you for your attention.

**Comment by HenrikFrystykNielsen** [comment]
Great idea and it would be super to have! One way to see it sooner is of course to send a PR :)
