### ISSUE TITLE
The WebHook signature provided by the 'X-Hub-Signature' header field does not match the value expected by the 'GitHubWebHookReceiver' receiver.

### ISSUE THREAD

**Issue by mariocatch** [aspnet/WebHooks#65]
I have a web server running with the GitHubWebHookReceiver integration.

I am testing posting to the controller action, and the action is being hit, but the response coming back is

```
{
  "Message": "The WebHook signature provided by the 'X-Hub-Signature' header field does not match the value expected by the 'GitHubWebHookReceiver' receiver. WebHook request is invalid."
}
```

I am posting with the following headers:

```
Content-Type: application/json
X-Hub-Signature: sha1=mytokenhere
```

I feel like the issue is coming from my usage of the `X-Hub-Signature` header. I added the following to the config for my app:

`<add key="MS_WebHookReceiverSecret_GitHub" value="mytokenhere" />`

`mytokenhere` is the same in both places (POST from client, and config on server), and it's something like: `3499c60eea227453c779de50fc84d315b9a55a20`

**Comment by HenrikFrystykNielsen** [comment]
What this means is that the X-Hub-Signature header which GitHub inserts into the WebHook request doesn't contain the right signature of the request body. This is normal if you put together the request manually. Alternatively what you can do is capturing a GitHub WebHook request using http://requestb.in and then submit that as-is to your localhost receiver for testing.

Hope this helps!

Henrik

**Comment by mariocatch** [comment]
@HenrikFrystykNielsen Thanks,

I used requestb.in to capture a WebHook from GitHub, and used that same data (body and headers) to send to my controller action.

The response is the same as my OP unfortunately. This leads me to believe that my App.config's setting is not correct.

Note, the value is exactly what I intercepted from the headers using requestb.in:

`<add key="MS_WebHookReceiverSecret_GitHub" value="87ae908d0ab2923ef3f2c3027a98658e014b5a48" />`

Do you have any other ideas?

**Comment by HenrikFrystykNielsen** [comment]
The value has to be the 'secret' that you set in GitHub when you create the WebHook.
