### ISSUE TITLE
WebHookManager request

### ISSUE THREAD

**Issue by alfhv** [aspnet/WebHooks#69]
Current implementation of WebHookManager, method VerifyWebHookAsync(), do basically 3 validations steps on a webhook:
- Secret is present and valid length
- webhook is on http or https
- webhook client can reply to "echo" request

So far is good, but ...I have my own webhook server and clients and I want to implement my own validation.
I'm then registering my own WebHookManager class on IDependencyScope and all works OK.

Point is that I would like to reuse same existing validations steps (3 points mentioned above) some times, and some other custom steps, in different scenarios depending of the client and other internal logic.

Could be possible to extract validation steps to methods and allow a nice inheritance on this class: WebHookManager ??

see basic sample here: [https://gist.github.com/alfhv/f0f57bab74bec6378514446449014250]

thanks,

**Comment by HenrikFrystykNielsen** [comment]
That makes a lot of sense! I like your example -- I can either do it or you can submit a PR -- both work fine :) 

thanks!

henrik

**Comment by HenrikFrystykNielsen** [comment]
Thanks for the pull request! Commit ID: 448fc48d6c5d48b6001dd764d1d70b490328dc1e

**Comment by HenrikFrystykNielsen** [comment]
Nugets have been updated -- look for version rc1d!
