### ISSUE TITLE
Stripe Connect

### ISSUE THREAD

**Issue by scurk1415** [aspnet/WebHooks#73]
I would like to ask if **Receivers.Stripe** has support for `Stripe Connect` events. I checked your code and noticed that you don't add the `Stripe-Account` header in `GetEventDataAsync` method.

Another question is, if we really need to double check for stripe event data, because we can't retrieve `account.application.deauthorize` event for example, it always throws an error (404 i think). So if a "Connected user" revokes his access we cant catch that event because the double check throws an error.

If anyone encountered this problem you can comment out `data = await GetEventDataAsync(request, id, notificationId);` in `StripeWebhooksReceiver.cs` line 110 and it should fix the issue. But let me remind you this is not a fix, just a temporary "problem solver" (for developement) until they fix this.

**Comment by HenrikFrystykNielsen** [comment]
It's been a little while but if I remember correctly, Stripe didn't send the whole event data but just a bit and then expected that you should follow up with a GET. Are you saying that you do get the full event in the WebHook request? If that is the case then we can secure it with a secret token in the URI and don't have to do the follow-up GET request.

**Comment by scurk1415** [comment]
Well the event `account.application.deauthorize` gets all the information needed (i don't know about other events as I didn't really need to catch those) but as I said we can't make a GET request for `account.application.deauthorize` and we also can't make any request for `Connected users` cause the code provided here doesn't have `Stripe-Account` header.

But if Stripe sends the whole event data back both of the above problems are solved if we remove the additional GET request.

**Comment by HenrikFrystykNielsen** [comment]
Ok, we can certainly make it optional on the receiver.

**Comment by scurk1415** [comment]
Is there any chance that you will check and update **Receivers.Stripe** anytime soon?
I would really appreciate if you do.

**Comment by HenrikFrystykNielsen** [comment]
It should be this week :)

**Comment by scurk1415** [comment]
Thank you very much :D

**Comment by HenrikFrystykNielsen** [comment]
@scurk1415, I checked in support for using Stripe in 'direct' mode which doesn't go back to Stripe using HTTP GET for the WebHook data: fdc6a7fa059eed2a6ceca39aece06898c18a0f84

It's currently in dev branch but should go out within a few days. If you have a chance then it would be great if you would be willing to verify.

Thanks!

Henrik

**Comment by HenrikFrystykNielsen** [comment]
Nugets have been updated -- look for version rc1d!
