### ISSUE TITLE
Request: extract generic persistence storage implementation

### ISSUE THREAD

**Issue by alfhv** [aspnet/WebHooks#74]
following request on #60, now we have a generic class DbWebHookStore where any concrete persistence storage implementation can derive from.
Problem, IMHO, this generic class is inside a concrete implementation project, SqlStorage, making any other concrete implementation, like OracleStorage, have a strong dependency of Microsoft.AspNet.WebHooks.Custom.SqlStorage.
I suggest to move files DbWebHookStore.cs and IRegistration.cs to a separate project, or inside Microsoft.AspNet.WebHooks.Custom project.
There is no impact on the SqlStorage implementation.
You can see this file move already done, as an example, in my own fork.
thanks,

**Comment by HenrikFrystykNielsen** [comment]
Thanks! It's not a bad idea but I think it is more cosmetic than anything as there is no difference in the dependencies between a 'SQL' and a 'DB' package. That is, the only difference is whether your implementation references the 'DB' package or the 'SQL' package. Are there any other differences?
