### ISSUE TITLE
Anyone managed to do this with Gmail?

### ISSUE THREAD

**Issue by georgiosd** [aspnet/WebHooks#77]
Documentation to set up gmail webhooks is terrible. 

Anyone managed to do this and can give some guidance?

**Comment by HenrikFrystykNielsen** [comment]
It's been a while since I looked at gmail webhooks. Do you have a pointer?

**Comment by georgiosd** [comment]
I have made some progress but still not 100% on the workflow. https://developers.google.com/gmail/api/guides/push

**Comment by aspnet-hello** [comment]
This issue was copied to aspnet/AspNetWebHooks#18

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspLabs#53
