### ISSUE TITLE
Is BitBucketReceiver broken?

### ISSUE THREAD

**Issue by garora** [aspnet/WebHooks#78]
I tried with my custom application as well as samples provided. With initial ```PR``` I've verified the functionality and test cases, it was working that time.

Don't know what happened it?

I registered BitBucket for ```push``` actions and set the URI https://bitbucketsamplereceiverapp.azurewebsites.net/api/webhooks/incoming/bitbucket/{id}?code=a5bfbf7b2d2c4ec07757183a61e9570611112ddc2724bde63ba85c0664c75403
Everything is placed as expected, but its throwing exception ```Could not find a valid configuration for WebHook receiver 'bitbucket' and instance 'id'. The setting must be set to a value between 32 and 128 characters long.```

In my config the key is present: ```<add key="MS_WebHookReceiverSecret_Bitbucket" value="a5bfbf7b2d2c4ec07757183a61e9570611112ddc2724bde63ba85c0664c75403"/>```

Is ```BitBucketReceiver``` functionality broken or I did anything wrong? Right now, I did not have my box with all ```ASP.NET WebHook``` source code so, I cant ```DEBUG``` locally.

**Comment by HenrikFrystykNielsen** [comment]
If present, can you try and remove the {id} part from the WebHook URI:

https://bitbucketsamplereceiverapp.azurewebsites.net/api/webhooks/incoming/bitbucket/{id}?code=a5bfbf7b2d2c4ec07757183a61e9570611112ddc2724bde63ba85c0664c75403

Henrik

**Comment by garora** [comment]
Thanks, its working fine with WebHook URI: https://bitbucketsamplereceiverapp.azurewebsites.net/api/webhooks/incoming/bitbucket/?code=a5bfbf7b2d2c4ec07757183a61e9570611112ddc2724bde63ba85c0664c75403

I've also corrected the sample page of BitBucket Receiver with this: PR https://github.com/aspnet/WebHooks/pull/80
