### ISSUE TITLE
Self host application with generic webhook dll

### ISSUE THREAD

**Issue by vovanb** [aspnet/WebHooks#81]
Hello
I have selfhost command line application with dll hosting generic webhook. How I can programmatecally assign setting from app.config :
`<add key="MS_WebHookReceiverSecret_GenericJson" value="83699ec7c1d794c0c780e49a5c72972590571fd8"/>`
Because if this setting is not in config file, I am getting below error:
`XXX.vshost.exe Error: 0 : Did not find any applications settings of the form 'MS_WebHookReceiverSecret_<receiver>'. To receive WebHooks, pleas
e add corresponding applications settings.
XXX.vshost.exe Error: 0 : Could not find a valid configuration  for WebHook receiver 'genericjson' and instance ''. The setting must be set to
a value between 32 and 128 characters long.`

**Comment by HenrikFrystykNielsen** [comment]
Config settings do not have to come from the config file. This is just the default behavior but you can easily change it to make the config settings come from wherever you want.

To change where config comes from, implement the [IWebHookReceiverConfig ](https://github.com/aspnet/WebHooks/blob/66ef4dad98f6cc07cb9733dd5d9d1d4e3e3345c2/src/Microsoft.AspNet.WebHooks.Receivers/WebHooks/IWebHookReceiverConfig.cs) interface and register it using [ReceiverServices.SetRecieverConfig()](https://github.com/aspnet/WebHooks/blob/master/src/Microsoft.AspNet.WebHooks.Receivers/Services/ReceiverServices.cs). 

If you are using DI then you can also register your IWebHookReceiverConfig implementation with that and it will get picked up.

Hope this helps,

Henrik

**Comment by vovanb** [comment]
Hi Henrick
It helped thanks a lot.
Sincerely,
Vladimir
(Sent from my mobile)
