### ISSUE TITLE
can we have one for Sendgrid

### ISSUE THREAD

**Issue by pooran** [aspnet/WebHooks#84]

**Comment by garora** [comment]
@pooran - Have you tried [CustomeReceiver](https://github.com/aspnet/WebHooks/tree/master/samples/CustomReceiver) sample for this.
Documentation for SendGrid WebHooks is avaialble here: [Hooks](https://sendgrid.com/docs/API_Reference/Webhooks/index.html)

**Comment by aspnet-hello** [comment]
This issue was copied to aspnet/AspNetWebHooks#19

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspLabs#52
