### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/WebHooks#85]
I try to get webhooks with paypal to run.

In VS wizard I set the secret of my REST api app so that I have in web.config:
`<add key="MS_WebHookReceiverSecret_Paypal" value="ENLJIoVBpDhoohG5AhqCFuNPddd40usZF49t3LradXvuRQZQmHcBfrpJZ5HVuDXpAj-V0gWzgpQX3lC2" />`

When running a webhook simulation from paypal:
https://webhooktestpaypal20160921072711.azurewebsites.net/api/webhooks/incoming/paypal/

I get a server 500 error. My PaypalWebHookHandler is not executed.

**Comment by doczoidberg** [comment]
webhooks should work without the paypal sdk?

**Comment by dougbu** [comment]
We do not plan to remove the Paypal SDK dependency in this receiver.
