### ISSUE TITLE
VS2015 new project format

### ISSUE THREAD

**Issue by yilativ** [aspnet/WebHooks#86]
Has anyone gotten this to work (or point me to an example) that has WebHooks working with the new appsettings.json/project.json?

Will me setting the keys with the appsettings.json just work?

Thank you!

**Comment by Eilon** [comment]
Please refer to https://github.com/aspnet/WebHooks/issues/5, where we will be working on adding support for ASP.NET Core. (The project.json file is no longer used, but appsettings.json still is.)
