### ISSUE TITLE
Deploying ASP.NET Webhooks on web server with IIS7

### ISSUE THREAD

**Issue by spyguyhi** [aspnet/WebHooks#87]
I have read through a few .NET Webhooks tutorials and since it is relatively new for .NET the examples are pretty limited.  I followed the tutorials to create a Webhook project in VS2013.  When I published the project I got three files (Global.asax. package.config, Web.config) and a bin folder with the dll's.  Here are a couple of the tutorials:

https://blogs.msdn.microsoft.com/webdev/2015/09/04/introducing-microsoft-asp-net-webhooks-preview/

http://www.dotnetcurry.com/aspnet/1245/aspnet-webhooks-receive-webhooks-from-github

All of the tutorial examples I have come across utilize Azure to publish their Webhook.  We have our own web server with IIS7.  I created a folder (appfolder) on our web server, another folder in it called mailchimp and placed the published files and bin folder in that folder so the path would be D:\appfolder\mailchimp.  I then created a new Site in IIS7 named apps.mysite.org pointing to D:\appfolder.  So as I believe the URI for the webhook should be http://apps.mysite.org/mailchimp/api/webhooks/incoming/mailchimp.  However, when I try to set the Webhook URL in my Mailchimp list it tells me "We couldn't connect to the specified URL.

What do I need to do to set up my web server to receive .NET Webhooks?  I would assume that the api/webhooks/incoming/mailchimp is a folder path but have not been able to find what I need to place in there.

Any assistance to go further would be awesome.

**Comment by mattscully** [comment]
@spyguyhi I'm not sure how much I can help, but you will want to be sure that things are configured correctly:

https://docs.asp.net/projects/webhooks/en/latest/receiving/receivers.html

Those docs also include instructions about turning on logging to troubleshoot issues more effectively.

You may also refer to the mailchimp sample (although this uses self-hosting) here:

https://github.com/aspnet/WebHooks/tree/master/samples/MailChimpReceiver.Selfhost

To test that things are running correctly, you can append `?echo=success` to the receiver URL in a browser and you should see "success" returned:

http://apps.mysite.org/mailchimp/api/webhooks/incoming/mailchimp?echo=success

I have yet to use one of the out-of-the-box receivers, but I have worked with the custom receivers and found that it is easy to miss a configuration step and have things not work.

**Comment by dougbu** [comment]
Question appears answered.
