### ISSUE TITLE
Release Notes?

### ISSUE THREAD

**Issue by mattscully** [aspnet/WebHooks#89]
Are there release notes for what has changed between the release candidates?  We are using the custom WebHook sender/receiver libraries and it would be helpful to know what has changed as we look to upgrade from 1.2.0-rc1b to 1.2.0-rc2.  I've looked through docs.asp.net, blogs, and github and couldn't find anything.

**Comment by HenrikFrystykNielsen** [comment]
Good question! Normally we just rely on the git history to see the differences between releases. All releases are marked with tags so it should be relatively easy to see the differences any two releases.

**Comment by mattscully** [comment]
@HenrikFrystykNielsen Sounds good.  I should have checked the tags previously, but that should be sufficient for now.  Thanks!
