### ISSUE TITLE
register with system account and trigger no matter user is

### ISSUE THREAD

**Issue by rainmakerho** [aspnet/WebHooks#93]
Hi sirs, 
   may i register with system account and trigger event no matter user is? 
currently trigger events only login user match with registrations user.
thanks.

**Comment by HenrikFrystykNielsen** [comment]
Yes, you can send events to any subset of your users using the model described here:

https://blogs.msdn.microsoft.com/webdev/2015/12/31/new-year-updates-to-asp-net-webhooks-preview/

Hope this helps!

Henrik

**Comment by rainmakerho** [comment]
Use NotifyAllAsync Method.
I got it. thank for your help.
