### ISSUE TITLE
Documentation moved / deleted

### ISSUE THREAD

**Issue by scorelocity** [aspnet/WebHooks#94]
It appears that the documentation that formerly resided at 
https://docs.asp.net/projects/webhooks/en/latest/ has been moved or deleted, causing a redirect to the root of the ASP.NET Core documentation. Adding a webhooks search term to the filter box returns nothing.

Granted, the previous documentation was little more than an index to a handful of blog posts, but it would be nice to know where the official documentation resides.

**Comment by scorelocity** [comment]
Revising my issue, further searching found the documentation here: https://docs.microsoft.com/en-us/aspnet/webhooks/. Perhaps just an update to the documentation link would be in order.

**Comment by garora** [comment]
@scorelocity - [PR #95](https://github.com/aspnet/WebHooks/pull/95) is created for new link.

**Comment by HenrikFrystykNielsen** [comment]
Thanks! I was wondering what happened to it :) I updated the fwlinks to point to the new location. If you see any that are still broken then please let me know. Thanks! Henrik
