### ISSUE TITLE
ASP.NET Web Forms Integration to Send Web Hooks to Subscribers

### ISSUE THREAD

**Issue by johndkane** [aspnet/WebHooks#99]
I would like to be able to integrate Web Hooks into legacy ASP.NET Web Forms applications to send hooks to subscribers, but am currently only finding examples in context of MVC.  Does Web Hooks support Web Forms and lack the documentation, or is it not feasible for use in Web Forms to send web hooks?

**Comment by HenrikFrystykNielsen** [comment]
John,

This is absolutely possible -- you might be able to glean it from the blog post on how to send notifications from a WebJob -- the principle would be much the same.

Let me know how it goes!

Henrik

[1] https://blogs.msdn.microsoft.com/webdev/2016/01/30/sending-asp-net-webhooks-from-azure-webjobs/
